package util;

/**
 * Enum for Maintain all page locators
 * 
 * @author UC202376
 *
 */
public enum OnePObjectMap {

	RID_LOGIN_BUTTON_XPATH("//img[@title='Login']"),
	RID_LOGIN_EMAIL_XPATH("//input[@id='email']"),
	RID_LOGIN_PWD_XPATH("//input[@id='password']"),
	RID_LOGIN_SUBMIT_BTN_XPATH("//*[@id='submitImage']/img"),
	RID_ENDNOTE_LINK_XPATH("//a[@id='header_link_endnote']"),

	ENW_CONTINUE_DIOLOG_BOX_XPATH("//*[@id='connect']"),
	ENW_CONTINUE_DIALOG_BOX_XPATH("//div[@id='noticeDialog']"),
	ENW_HEADER_XPATH("//h1[@class='ne-nav-logo']"),
	WOS_HEADER_XPATH("//div[@class='logoBar']//img[@title='Web of Science']"),
	ENW_PROFILE_USER_ICON_XPATH("//img[@id='proSmallImg']"),
	ENW_PROFILE_USER_ACCOUNT_LINK_CSS("span[class='fa fa-cog profile_account_link']"),
	ENW_PROFILE_USER_NAME_XPATH("//span[@class='profile_title']"),
	IMAGE_USER_XPATH("//img[@id='proImg']"),
	IMAGE_ICON_PROFILE_IN_NEON_XPATH("//div/button/img[@class='ne-user-profile-image']"),
	SEND_FEEDBACK_COUNTRY_SELECTION_XPATH("//div[@class='modal-header wui-modal__header ng-scope']"),
	COUNTRY_SELECT_IN_NEON(".//*[@id='countrySelect']"),

	ENW_PRIVACY_LINK_XPATH("//a[contains(text(),'Privacy')]"),
	ENW_TERMS_OF_USE_XPATH("//a[contains(text(),'Terms of use')]"),
	ENW_HELP_LINK("Help"),
	ENW_HELP_XPATH("//a[contains(text(),'Help')]"),
	ENW_FEEDBACK_XPATH("//a[contains(text(),'Feedback')]"),
	ENW_SEND_FEEDBACK_LINK_XPATH("//a[@class='feedback-link__anchor']"),
	ENW_OPTIONS_TAB_LINK("Options"),
	ENW_PROFILE_TAB_LINK("Profile Information"),
	ENW_OPTIONS_TAB_XPATH("//*[@id='enwHeader']//a[@id='lgLink6' and contains(text(),'Options')]"),
	ENW_PROFILE_TAB_XPATH("//a[contains(text(),'Profile Information')]"),
	FEEDBACK_THANKU_PAGE_XPATH("//h3[contains(text(),'Thank You')]"),
	ENW_PROFILE_FIRST_NAME_XPATH("//input[@id='firstname']"),
	ENW_PROFILE_LAST_NAME_XPATH("//input[@id='lastname']"),
	ENW_SIGNIN_BTN_CSS("button[class*='login-button']"),
	COMMON_SEND_FEEDBACK_ENDNOTE_TEAM("//A[@CLASS='FEEDBACK-LINK__ANCHOR NG-BINDING']"),
	COMMON_FEEDBACK_COMMENTS_XPATH("//*[@id='msg']"),
	COMMON_FEEDBACK_SUBMIT_BTN_XPATH("//button[contains(text(),'Submit')]"),
	COMMON_FEEDBACK_SENT_CONFIRMATION_XPATH("//*[@CLASS('NG-BINDING' AND CONTAINS(TEXT(),'YOUR FEEDBACK HAS BEEN SENT')]"),
	COMMON_FEEDBACK_CLOSE_XPATH(".//button[@class='wui-btn wui-btn--primary']"),
	COMMON_ENW_REPORT_PROBLEM_XPATH("//a[contains(text(),'Report a problem or submit a support request')]"),
	EXPECTED_PAGE_DISPLAYED_XPATH(".//*[@ID('HEADER']/H1/A[1]"),
	EXPECTED_PAGE_DISPLAYED1_XPATH("//*[@title='science home']"),

	NEON_SIDE_FEEDBACKHELP_XPATH("//*[@class('ne-profile-flyout__link' and contains(text(),'Feedback')]"),
	NEON_SIDE_SUBMIT_BUTTON_CSS("//button[class='wui-btn wui-btn--primary wui-btn--hook']"),
	WOS_HOMEPAGE_ENDNOTE_LINK(".//*[@id='HS_EndNoteLink_signedin']"),
	WOS_SESSION_ALREADYEXISTS(".//*[@id='WoKerror']/div[1]/table[2]/tbody/tr/td[2]/p/a[1]"),
	FB_PAGE_LOGIN_NAME("button[name='login']"),
	DID_YOU_KNOW_LETS_GO_BUTTON_XPATH("//button[@class='wui-btn wui-btn--secondary wui-btn--modal-footer button-color-secondary']"),
	ENW_FB_PROFILE_FLYOUT_CIRCLE_XPATH("//img[@id='proSmallImg']"),
	ENW_FB_SIGNOUT_XPATH("//li[@class='pull-right']"),
	ENW_YES_I_HAVE_AN_ACCOUNT_BUTTON_CSS("button[class='wui-btn wui-btn--secondary button-color-secondary']"),
	ENW_LINK_ACCOUNTS_EMAIL_XPATH("//input[@name='email']"),
	ENW_LINK_ACCOUNTS_PASSWORD_XPATH("//input[@name='password']"),
	ENW_LINK_ACCOUNTS_DONE_BUTTON_XPATH("//button[@class='wui-btn wui-btn--secondary wui-btn--modal-footer button-color-secondary']"),
	ENW_LINK_ACCOUNTS_DONE_BUTTON_CSS("form#linkAccounts button"),

	ENW_FB_LOGIN_BUTTON_XPATH("//button[@id='loginbutton']"),
	ENW_CONTINUE_BUTTON_XPATH("//div[@id='continue']"),
	ENW_FB_PROFILE_IMGCIRCLE_XPATH("//img[@id='proSmallImg']"),
	ENW_FB_PROFILE_IMGCIRCLE_ACCOUNT_XPATH("//a[contains(.,'Account')]"),
	ENW_FB_PROFILE_FLYOUT_SIGNOUT_XPATH("//a[contains(.,'Sign out')]"),
	ENW_BACK_TO_ENDNOTE_BUTTON_XPATH("//span[contains(.,'Back to EndNote')]"),
	ENW_RESEND_ACTIVATION_BUTTON_CSS("button[event-action='resend-activation']"),
	ENW_RESEND_ACTIVATION_DONE_BUTTON_CSS("button[event-action='resend-activation-done']"),
	ENW_UNVERIFIED_MESSAGE_BUTTON_CSS("h2[class='login-title']"),

	// sendtoendnote locators
	NEON_RECORDVIEW_NOTES1_XPATH("//span[text()='Times Cited']//preceding::span[1]"),
	NEON_RECORDVIEW_NOTES2_XPATH("//span[text()='Cited References']//preceding::span[1]"),
	NEON_RECORDVIEW_TITLE_XPATH("//div[@class='ne-publication__header']//h2"),
	NEON_RECORDVIEW_JOURNAL_XPATH("//div[@class='ne-publication__metadata ng-binding']"),
	NEON_RECORDVIEW_VOLUME_XPATH("//div[@ng-show='record.volume != null']/span[2]"),
	NEON_RECORDVIEW_ISSUE_XPATH("//div[@ng-show='record.issue != null']/span[2]"),
	NEON_RECORDVIEW_PAGES_XPATH("//div[@ng-show='record.pages != null']/span[2]"),
	NEON_RECORDVIEW_POSTAUTHOR_CSS("div[class='ne-publication__header'] div[class='wui-subtitle ne-user-profile-object-name ng-scope'] a"),
	NEON_RECORDVIEW_PATENT_AUTHOR1_XPATH("//div[@class='wui-descriptor']/span[@class='ng-binding ng-scope'][1]"),
	NEON_RECORDVIEW_PATENT_AUTHOR2_XPATH("//div[@class='wui-descriptor']/span[@class='ng-binding ng-scope'][2]"),
	NEON_RECORDVIEW_PATENT_AUTHOR3_XPATH("//div[@class='wui-descriptor']/span[@class='ng-binding ng-scope'][3]"),
	NEON_RECORDVIEW_PATENT_ASSIGNEE_CSS("span[ng-bind-html='::assign']"),
	NEON_RECORDVIEW_POST_NAME_XPATH("//h2[@class='wui-content-title wui-content-title--ne-publication ng-binding']"),
	NEON_RECORDVIEW_PATENT_ABSTRACT_CSS("p[class='ne-publication__body wui-large-text wui-large-text--serif ng-binding']"),
	NEON_RECORDVIEW_POST_ABSTRACT_XPATH("//div[@class='ne-publication__body--post wui-large-text wui-large-text--serif fr-view']"),
	NEON_RECORDVIEW_PATENT_IPC_CURRENT_CSS("p[class*='ne-publication__body'] span[class*='ng-binding ng-scope']"),
	ENW_KEYWORDS_XPATH(".//*[@id='keywords_tdBg']/span"),
	ENW_UNFILEDFOLDER_LINK_XPATH("//div[@id='idFolderLink_1']/a"),
	// ENW_RECORD_LINK_XPATH("//a[@title='Go to reference' and contains(text(),'Fostering synergy between cell
	// biology')]"),
	ENW_RECORD_LINK_XPATH(".//*[@id='ref_main']/tr[6]/td[4]/a"),
	ENW_SORTBY_OPTIONS_ID("sort_By"),

	ENW_RECORD_REFERENCETYPE_XPATH("//tr[@id='showRefName']/td[1]"),
	ENW_RECORD_REFERENCETYPE_VALUE_XPATH("//tr[@id='showRefName']/td[2]"),

	ENW_RECORD_URL_XPATH("//tr[@id='url_tr']/td[1]/span"),
	ENW_RECORD_URL_VALUE_XPATH("//tr[@id='url_tr']/td[2]//span[contains(text(), 'stable')]"),
	ENW_RECORD_AUTHOR_XPATH("//tr[@id='author_tr']/td[1]/span"),

	ENW_RECORD_AUTHOR_VALUE_CSS("span[id='spnau']"),
	ENW_RECORD_PATENT_AUTHOR1_VALUE_CSS("span[id='author_tdBg'] span:nth-child(1)"),
	ENW_RECORD_PATENT_AUTHOR2_VALUE_CSS("span[id='author_tdBg'] span:nth-child(3)"),
	ENW_RECORD_PATENT_AUTHOR3_VALUE_CSS("span[id='author_tdBg'] span:nth-child(5)"),

	ENW_RECORD_TITLE_XPATH("//tr[@id='title_tr']/td[1]/span"),
	ENW_RECORD_TITLE_VALUE_XPATH("//tr[@id='title_tr']/td[2]/div"),

	ENW_RECORD_JOURNAL_XPATH("//tr[@id='secondary_title_tr']/td[1]/span"),
	ENW_RECORD_JOURNAL_VALUE_XPATH("//tr[@id='secondary_title_tr']/td[2]/div"),

	ENW_RECORD_VOLUME_XPATH("//tr[@id='volume_tr']/td[1]/span"),
	ENW_RECORD_VOLUME_VALUE_XPATH("//tr[@id='volume_tr']/td[2]/div"),

	ENW_RECORD_ISSUE_XPATH("//tr[@id='number_tr']/td[1]/span"),
	ENW_RECORD_ISSUE_VALUE_XPATH("//tr[@id='number_tr']/td[2]/div"),

	ENW_RECORD_ABSTRACT_XPATH("//tr[@id='abstract_tr']/td[1]/span"),
	ENW_RECORD_ACCESSIONNUMBER_XPATH("//tr[@id='accession_number_tr']/td[1]/span"),

	ENW_RECORD_NOTES_XPATH("//tr[@id='notes_tr']/td[1]/span"),
	ENW_RECORD_NOTES_VALUE_XPATH("//tr[@id='notes_tr']/td[2]/div"),
	ENW_RECORD_LASTUPDATEDNO_XPATH("//tr[@id='date_tr']/td[1]/span"),
	ENW_RECORD_ASSIGNEE_VALUE_CSS("div [id='publisher']"),
	ENW_RECORD_ABSTRACT_VALUE_CSS("div[id='abstract']"),
	ENW_RECORD_TITLE_ENTRY_XPATH(".//*[@id='title']"),
	// PATENTS RECORDS
	ENW_RECORD_INVENTOR_XPATH("//tr[@id='author_tr']/td[1]/span"),
	ENW_RECORD_ASSIGNEE_XPATH("//tr[@id='publisher_tr']/td[1]/span"),
	ENW_RECORD_PATENTNO_XPATH("//tr[@id='isbn_tr']/td[1]/span"),
	ENW_RECORD_KEYWORDS_XPATH("//tr[@id='keywords_tr']/td[1]/span"),
	ENW_SHOWALLFILEDS_LINK_XPATH("//a[@title='Show All Fields']/span"),
	NEON_RECORDVIEW_PATENTS_NOTES1_XPATH("//span[text()='Cited Patents']//preceding::span[1]"),
	NEON_RECORDVIEW_PATENTS_NOTES2_XPATH("//span[text()='Cited Articles']//preceding::span[1]"),
	// Profile page locators
	HOME_ONEP_APPS_CSS("i[class='wui-icon wui-icon--app']"),
	HOME_PROJECT_NEON_APP_SWITCHER_LINKS_CSS("li[class='ne-app-switcher-flyout__list-item'] a"),
	HOME_PROJECT_NEON_APP_SWITCHER_BAU_LINK_GO_CSS("span[class*='secondary']"),
	HOME_PROJECT_NEON_PROFILE_PRIVACY_STATEMENT_LINK("Privacy"),
	HOME_PROJECT_NEON_PROFILE_TERMS_OF_USE_LINK("Terms of Use"),
	HOME_PROJECT_NEON_APP_RECORD_VIEW_DETALIS_XPATH("//a[contains(text(),'View in Web of Science')]"),
	HOME_PROJECT_NEON_APP_RECORD_VIEW_DETALIS_BACKTOPN_CSS("a[title='Back to Project Neon']"),
	HOME_PROJECT_NEON_OWN_PROFILE_COMMENTS_LIKE_XPATH("//span[@class='webui-icon webui-icon-like']/following-sibling::span"),
	HOME_PROJECT_NEON_APP_PROFILE_COMMENTS_CSS("li[class='search-heading tabs ng-isolate-scope active']"),
	HOME_PROJECT_NEON_OWN_PROFILE_INTEREST_SKILLS_CSS("a[class='remove-button ng-binding ng-scope']"),
	HOME_PROJECT_NEON_AUTHORING_PREVENT_BOT_COMMENT_CSS("div[class='ne-create-comment__content'] div[class*='wui-textarea__error'] span"),
	HOME_PROJECT_NEON_PROFILE_FOLLOWING_CSS("a[class='ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_NAME_CSS("span[class='ne-profile-object-title ng-scope']"),
	HOME_PROJECT_NEON_RECORD_VIEW_TITLE_CSS("h3[class='ng-binding']"),
	HOME_PROJECT_NEON_RECORD_VIEW_ARTICLE_WATCH_CSS("button[class^='btn btn-default pub-action-btn']"),
	HOME_PROJECT_NEON_WATCHLIST_DOCINFO_CSS("span[class^='doc-info']"),
	HOME_PROJECT_NEON_WATCHLIST_ARTICLE_COUNT_CSS("h2.headline span"),
	HOME_PROJECT_NEON_WATCHLIST_MORE_BUTTON_XPATH("//button[@class='btn webui-btn-primary']"),
	HOME_PROJECT_NEON_ARTICLE_SEARCH_MORE_BUTTON_CSS("button[class='btn webui-btn-primary ng-binding']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_SHARE_CSS("button[class='btn btn-default pub-action-btn dropdown-toggle']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_SHARE_ON_TWITTER_CSS("i[class='fa fa-twitter share-menu-icon']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_TWITTER_USERNAME_CSS("input#username_or_email"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_TWITTER_PASSWORD_CSS("input#password"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_TWITTER_LOGIN_CSS("input[value='Log in and Tweet']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_TWEET_DESC_CSS("textarea#status"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_TWEET_CSS("input[value='Tweet']"),

	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_SHARE_ON_LI_CSS("i[class='fa fa-linkedin share-menu-icon']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_LI_USERNAME_CSS("input#session_key-oauthAuthorizeForm"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_LI_PASSWORD_CSS("input#session_password-oauthAuthorizeForm"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_LI_LOGIN_CSS("input[name='authorize']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_LI_SHARE_CSS("input[class='btn-primary'][value='Share']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_SHARE_ON_GOOGLE_CSS("i[class='fa fa-google-plus share-menu-icon']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_GOOGLE_USERNAME_CSS("input#Email"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_GOOGLE_NEXT_CSS("input#next"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_GOOGLE_PASSWORD_CSS("input#Passwd"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_GOOGLE_LOGIN_CSS("input#signIn"),

	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_GOOGLE_SHARE_XPATH("//div[contains(.,'Post') and @role='button']"),

	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_SHARE_ON_FB_CSS("i[class='fa fa-facebook share-menu-icon']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_FB_USERNAME_CSS("input#email"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_FB_PASSWORD_CSS("input#pass"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_FB_LOGIN_CSS("input[value='Log In']"),
	HOME_PROJECT_NEON_ARTICLE_RECORD_VIEW_FB_SHARE_LINK_CSS("*[type='submit'][name*='CONFIRM']"),

	HOME_PROJECT_NEON_ARTICLE_PROFILE_METADATA_TAG("h6"),
	HOME_PROJECT_NEON_PROFILE_INTEREST_AND_SKILLS_CSS("li[class='interest-or-skill ng-binding ng-scope']"),
	//HOME_PROJECT_NEON_SEARCH_BOX_CSS("div[class='ne-main-nav'] input[class^='wui-search-bar__input']"),
	HOME_PROJECT_NEON_SEARCH_BOX_CSS("input[placeholder='Search Articles, Patents, People and Posts']"),
	HOME_PROJECT_NEON_SEARCH_CLICK_CSS("div[class='ne-main-nav'] button[title='Search'] i[class='fa fa-search']"),
	HOME_PROJECT_NEON_SEARCH_PEOPLE_CSS("li[class^='wui-side-menu__list-item']"),
	//HOME_PROJECT_NEON_PROFILE_IMAGE_CSS("div[class^='dropdown ne-profile-flyout'] a[data-toggle='dropdown']"),
	HOME_PROJECT_NEON_PROFILE_IMAGE_CSS("div[class^='ne-profile-flyout'] a[class='dropdown-toggle']"),
	HOME_PROJECT_NEON_PROFILE_CSS("div[class*='ne-profile-flyout__menu'] a[href^='#/profile']"),
	HOME_PROJECT_NEON_PROFILE_SIGNOUT_LINK("Sign out"),
	HOME_PROJECT_NEON_PROFILE_ACCOUNT_LINK("Account"),
	HOME_PROJECT_NEON_PROFILE_HELP_LINK("Help & Feedback"),
	HOME_PROJECT_NEON_SEARCH_PROFILE_TICKMARK_CSS("div[class='wui-card__body-content'] ne-user-follow-unfollow button span"),
	HOME_PROJECT_NEON_OTHER_PROFILE_TICKMARK_CSS("button[class='btn btn-link fadeinout ne-user-follow-unfollow ne-user-follow-unfollow--large']"),
	HOME_PROJECT_NEON_SEARCH_PROFILE_TOOLTIP_CSS("ne-user-follow-unfollow button"),
	HOME_PROJECT_NEON_SEARCH_PROFILE_TITLE_CSS("div[class*='ne-user-profile-object-name ng-scope'] a"),
	HOME_PROJECT_NEON_SEARCH_PROFILE_METADATA_CSS("div[class='wui-descriptor wui-descriptor__profile--medium ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_TITLE_CSS("h2[class*='user-profile-name']"),
	HOME_PROJECT_NEON_PROFILE_ROLE_METADATA_CSS("span[ng-if*='user.role']"),
	HOME_PROJECT_NEON_PROFILE_PRIMARYINSTITUTION_METADATA_CSS("span[ng-if*='user.primaryInstitution']"),
	HOME_PROJECT_NEON_PROFILE_LOCATION_METADATA_CSS("span[ng-if*='user.location']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_CSS("button[ng-show='vm.shouldShowEditButton()']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_FIRST_NAME_CSS("input[name='firstName']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_LAST_NAME_CSS("input[name='lastName']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_ROLE_CSS("input[aria-label*='Role']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_PI_CSS("input[ng-model*='vm.field']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_PRIINS_CSS("input[placeholder='+ Institution']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_COUNTRY_CSS("input[placeholder='+ Country']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_SUMMARY_CSS("textarea[placeholder='Add a summary']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_CANCEL_CSS("button[class='wui-btn wui-btn--secondary']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_UPDATE_CSS("button[class='wui-btn wui-btn--primary']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_FIRST_NAME_ERROR_MESSAGE_CSS("div[ng-messages='userForm.firstName.$error']"),
	HOME_PROJECT_NEON_PROFILE_EDIT_LAST_NAME_ERROR_MESSAGE_CSS("div[ng-messages='userForm.lastName.$error']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_BUTTON_CSS("button[ng-click*='UserProfileImage']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_SELECT_IMAGE_PLINK("image"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_CHANGE_IMAGE_LINK("Change image"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_MODAL_WINDOW_CSS("div[modal-window='modal-window']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_MODAL_WINDOW_BROWSE_CSS("button[id='browser-file']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_MODAL_WINDOW_CLOSE_CSS("button[class='wui-modal__close-btn']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_MODAL_WINDOW_CANCEL_CSS("button[ng-click='ImagePicker.cancel()']"),
	HOME_PROJECT_NEON_PROFILE_PICTURE_MODAL_WINDOW_UPDATE_CSS("button[ng-click='ImagePicker.ok()']"),
	HOME_PROJECT_NEON_PROFILE_CTA_WHITE_BOX_CSS("div[class='source-sans popover-content']"),

	HOME_PROJECT_NEON_PROFILE_TAB_POSTS_CSS("a[data-event-category='profileposts']"),
	HOME_PROJECT_NEON_PROFILE_TAB_COMMENTS_CSS("a[data-event-category='profilecomments']"),
	HOME_PROJECT_NEON_PROFILE_TAB_FOLLOWERS_CSS("a[data-event-category='profilefollowers']"),
	HOME_PROJECT_NEON_PROFILE_TAB_FOLLOWING_CSS("a[data-event-category='profilefollowing']"),
	HOME_PROJECT_NEON_PROFILE_TAB_WATCHLIST_CSS("a[data-event-category='profilewatchlists']"),
	HOME_PROJECT_NEON_PROFILE_TAB_COMMENT_APPRECIATE_CSS("button[ng-click*='appreciateThis']"),
	HOME_PROJECT_NEON_PROFILE_PUBLISH_A_POST_BUTTON_CSS("a[redirect-state='profile.post']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_MODAL_CSS("div[class='modal-content']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_MODAL_DRAFTS_LINK_XPATH("//div[@class='modal-content']/descendant::a[@class='ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_TITLE_CSS("textarea[placeholder^='Give your post a title']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_CONTENT_CSS("div[class='fr-element fr-view']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_ERROR_CSS("div[class^='wui-textarea__error ne-publication-posting__info ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_CSS("button[data-event-action='cancel'][title='Close']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_PUBLISH_CSS("button[data-event-action='publish']"),
	HOME_PROJECT_NEON_PROFILE_POST_TITLE_CSS("div[class^='wui-content-title']"),
	HOME_PROJECT_NEON_PROFILE_POST_COUNT_CSS("ul[class='wui-side-menu__list'] li[class^='wui-side-menu__list-item']:nth-child(1) span[class='wui-side-menu__badge ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_DRAFT_POST_COUNT_CSS("ul[class='wui-side-menu__list'] li[class^='wui-side-menu__list-item']:nth-child(2) span[class='wui-side-menu__badge ng-binding']"),
	HOME_PROJECT_NEON_VIEW_POST_EDIT_XPATH("//button[text()='Edit']"),
	HOME_PROJECT_NEON_VIEW_POST_SHARE_CSS("i[class^='webui-icon webui-icon-share']"),
	HOME_PROJECT_NEON_VIEW_POST_WATCH_CSS("i[class^='webui-icon webui-icon-watch']"),
	HOME_PROJECT_NEON_VIEW_POST_STOP_WATCH_CSS("i[class^='webui-icon webui-icon-watch'][class$='watching']"),
	HOME_PROJECT_NEON_VIEW_POST_SHARE_FACEBOOK_CSS("a[label='Share on Facebook']"),
	HOME_PROJECT_NEON_VIEW_POST_SHARE_LINKEDIN_CSS("a[label='Share on LinkedIn']"),
	HOME_PROJECT_NEON_VIEW_POST_SHARE_TWITTER_CSS("a[event-category='share-twitter-posts']"),
	HOME_PROJECT_NEON_HEADER_WATCHLIST_CSS("a[href='#/watchlist']"),
	HOME_PROJECT_NEON_HEADER_NEWSFEED_CSS("a[href='#/home']"),
	HOME_PROJECT_NEON_HEADER_NEWSFEED_XPATH("//span[contains(@class,'ng-binding') and contains(.,'Newsfeed')]"),
	HOME_PROJECT_NEON_HEADER_PUBLISH_A_POST_CSS("a[redirect-state='profile.post']"),

	HOME_PROJECT_NEON_PROFILE_REMOVE_TOPIC_CSS("a[ng-click='$removeTag()']"),
	HOME_PROJECT_NEON_PROFILE_ADD_TOPIC_CSS("input[placeholder='Add a Topic']"),
	HOME_PROJECT_NEON_PROFILE_ADD_TOPIC_TYPEAHEAD_CSS("div[class='autocomplete ng-scope'] ul li"),
	HOME_PROJECT_NEON_VIEW_POST_APPRECIATION_COUNT_CSS("div[class='ne-publication-sidebar__metrics'] button[class*='wui-icon-metric'] span[class='wui-icon-metric__value ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_INSERT_LINK_URL_TEXT_BOX_CSS("input[placeholder='URL']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_INSERT_LINK_URL_INSERT_CSS("button[class='fr-command fr-submit']"),
	HOME_PROJECT_NEON_VIEW_POST_APPRECIATION_CSS("div[class='ne-publication-sidebar__metrics']  button[class*='wui-icon-metric'] i"),

	HOME_PROJECT_NEON_PROFILE_TAGLIST_PUBLISH_A_POST_BUTTON_CSS("button[id='posting']"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_TITLE_CSS("h2[class^='wui-content-title']"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_PROFILE_TILE_CSS("div[class='ne-publication__header'] div[class='wui-subtitle ne-user-profile-object-name ng-scope'] a"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_PROFILE_METADATA_CSS("div[class='ne-publication__header'] div[class='ne-user-profile-object-info'] div[class^='wui-descriptor']"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_CONTENT_CSS("div[class*='ne-publication__body--post wui-large-text wui-large-text--serif fr-view']"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_TIMESTAMP_CSS("div[class='ne-publication__header'] span[class^='ne-publication__metadata']"),
	HOME_PROJECT_NEON_PROFILE_TABS_DEFAULT_MESSAGE_CSS("div[data-ng-show='vm.isCurrentUsersProfile']"),
	// HOME_PROJECT_NEON_PROFILE_POST_DETAILS_TIMESTAMP_CSS("div[data-ng-show='vm.hasPosts'] p"),
	HOME_PROJECT_NEON_PROFILE_POST_DETAILS_LIKE_XPATH("//div[@data-ng-show='vm.hasPosts']/div[2]/div[1]"),
	HOME_PROJECT_NEON_PROFILE_POST_DETAILS_COMMENTS_XPATH("//div[@data-ng-show='vm.hasPosts']/div[2]/div[2]"),
	HOME_PROJECT_NEON_PROFILE_POST_DETAILS_WATCH_CSS("div[data-ng-show='vm.hasPosts'] button[data-event-category='watchlist-watch-item']"),

	HOME_PROJECT_NEON_WATCHLIST_RECORDS_CSS("span[class='webui-icon-btn-text']"),
	HOME_PROJECT_NEON_WATCHLIST_CSS("h2[class='search-results-title']"),
	HOME_PROJECT_NEON_PROFILE_PUBLISH_A_POST_DISCARD_CSS("button[ng-click='vm.close(vm.buttons.DISCARD)']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_INSERT_LINK_BUTTON_CSS("button[data-cmd='insertLink'] i"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_AUTHORNAME_CSS("div[class='wui-subtitle ne-user-profile-object-name ng-scope'] a"),
	HOME_PROJECT_NEON_POST_WATCH_CSS("button[class='pull-left btn webui-icon-btn watchlist-toggle-button']"),
	HOME_PROJECT_NEON_POST_WATCH_CLOSE_CSS("button[ng-click='WatchlistModal.close()']"),
	HOME_PROJECT_NEON_PROFILE_PI_TYPEAHEAD_CSS("ul[ng-show='isOpen() && !moveInProgress']"),
	//HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_DISCARD_XPATH("//div[@class='modal-dialog']/descendant::button[@event-action='cancel' and contains(.,'Discard')]"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_DISCARD_XPATH("//button[@class='wui-btn wui-btn--secondary ng-binding']"),
	//HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_KEEP_DRAFT_XPATH("//div[@class='modal-dialog']/descendant::button[@event-action='cancel' and contains(.,'Keep draft')]"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_KEEP_DRAFT_XPATH("//button[@class='wui-btn wui-btn--secondary ng-binding ng-scope']"),
	HOME_PROJECT_NEON_PROFILE_COUNTRY_METADATA_CSS("span[ng-if*='location']"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_COMMENTS_COUNT_XPATH("//div[contains(@class,'wui-icon-metric') and contains(.,'Comments')]/descendant::span[@class='wui-icon-metric__value ng-binding']"),
	HOME_PROJECT_NEON_VIEW_POST_FOLLOW_BUTTON_CSS("div[class='ne-publication__header'] button[class*='ne-user-follow-unfollow']"),
	HOME_PROJECT_NEON_VIEW_POST_COMMENT_CSS("div[class='ne-comment-list__comment-content']"),
	HOME_PROJECT_NEON_PROFILE_COMMENTS_COUNT_CSS("a[data-event-category='profilecomments'] span[class*='ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_FOLLOWERS_COUNT_CSS("a[data-event-category='profilefollowers'] span[class='ng-binding']:nth-child(2)"),
	HOME_PROJECT_NEON_PROFILE_FOLLOWING_COUNT_CSS("a[data-event-category='profilefollowing'] span[class='ng-binding']:nth-child(2)"),
	HOME_PROJECT_NEON_PROFILE_TABS_CSS("li[ng-repeat='tab in vm.detailTabs']"),
	HOME_PROJECT_NEON_PROFILE_TABS_RECORDS_CSS("div[class='wui-card__content']"),

	HOME_PROJECT_NEON_RECORD_VIEW_POST_LIKE_COUNT_XPATH("//div[contains(@class,'post-stat')]/descendant::div[contains(@class,'doc-info')][2]/span[contains(@class,'stat-count')][1]"),
	HOME_PROJECT_NEON_RECORD_VIEW_POST_LIKE_XPATH("//div[@class='ne-publication-sidebar__metrics']/button/i"),
	HOME_PROJECT_NEON_PROFILE_POST_LIKE_CSS("span[class='wui-icon-metric__value ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_POST_TIMESTAMP_XPATH("//wui-timestamp[contains(@date,'post.keydate')]/span"),
	HOME_PROJECT_NEON_PROFILE_SUMMARY_CSS("div[ng-hide='vm.shouldShowSummaryInput()'] p"),
	HOME_PROJECT_NEON_PROFILE_DRAFT_POST_FIRST_TITLE_CSS("a[ng-click^='vm.titleClicked']"),
	HOME_PROJECT_NEON_PROFILE_DRAFT_POST_FIRST_EDIT_CSS("div[class*='wui-card__footer-content'] a"),
	HOME_PROJECT_VIEW_POST_FLAG_BUTTON_CSS("button[event-category='post-flag'] i"),
	HOME_PROJECT_VIEW_POST_DELETE_BUTTON_CSS("button[id='deleting']"),
	HOME_PROJECT_VIEW_POST_DELETE_CONFIRMATION_BUTTON_CSS("div[class='modal-content'] button[ng-click='close()']"),
	HOME_PROJECT_NEON_PROFILE_COMMENT_TIMESTAMP_CSS("span[class*='time-stamp']"),
	HOME_PROJECT_NEON_PROFILE_HCR_BADGE_CSS("div[class*='ne-user-profile-object-name']"),
	HOME_PROJECT_NEON_PROFILE_WATCHLIST_CSS("button[class*='wui-icon-only-btn ne-action-dropdown__add-button']"),

	//KR
	HOME_PROJECT_NEON_ADD_VIDEO_BUTTON_XPATH("//i[@class='fa fa-video-camera']"),
	HOME_PROJECT_NEON_ADD_URL_BUTTON_XPATH("//input[contains(@id,'fr-video-by-url-layer-text-')]"),
	HOME_PROJECT_NEON_INSERT_URL_XPATH("//button[@class='fr-command fr-submit' and @data-cmd='videoInsertByURL']"),
	HOME_PROJECT_NEON_VIDEO_BOX_XPATH("//span[@class='fr-video fr-fvc fr-dvb fr-draggable']/iframe"),
	HOME_PROJECT_NEON_ADD_IMAGE_BTN_XPATH("//a[@class='fr-floating-btn']"),
	HOME_PROJECT_NEON_IMAGE_SELECTOR_BTN_XPATH("//i[@class='fa fa-image']"),
	HOME_PROJECT_NEON_IMAGE_IN_POST_XPATH("//img[contains(@class,'fr-fic fr-dii')]"),
	
	//wui-timestamp[contains(@date,'post.keydate'])/span
	HOME_PROJECT_NEON_DELETE_POST_CONFIRMATION_XPATH("//span[text()='This post has been removed by the member.']"),
	
	
	HOME_PROJECT_SECTION_HEADING_LABEL("//button[@class='btn dropdown-toggle ne-search-dropdown-btn ng-binding']"),
	HOME_PROJECT_SELECT_PEOPLE_FOR_SEARCH_IN_DROPDOWN_XPATH("//div[@class='input-group-btn open']//ul[@class='dropdown-menu']//li[4]//a"),
	HOME_PROJECT_SEARCH_TEXTBOX_XPATH("//input[@placeholder='Search Articles, Patents, People and Posts']"),
	HOME_PROJECT_SEARCH_BUTTON_XPATH("//div[@class='ne-main-nav']/descendant:: button[@title='Search']/descendant::i[@class='fa fa-search']"),
	HOME_PROJECT_PEOPLE_LINK("//div[@class='wui-card__body-content']/descendant::a[@class='ng-binding ng-scope']"),
	HOME_PROJECT_NEON_RECORD_VIEW_DRAFT_POST_DELETE_XPATH("//div[@class='wui-card__content' and contains(.,'TITLE')]/descendant::button[@id='deleting']"),
	HOME_PROJECT_NEON_RECORD_VIEW_DRAFT_POST_EDIT_XPATH("//div[@class='wui-card__content' and contains(.,'TITLE')]/descendant::a[contains(@class,'wui-mini-btn--secondary')]"),
	HOME_PROJECT_NEON_RECORD_VIEW_DRAFT_POST_DELETE_CONFIRMATION_CSS("div[class='modal-content'] button[ng-click='close()']"),
	HOME_PROJECT_SEARCH_RESULTS_ARTICLES_LINK("//ne-article-results//a[@class='ng-binding']"),
	HOME_PROJECT_SEARCH_RESULTS_PATENTS_LINK("//ne-patent-results//a[@class='ng-binding']"),
	HOME_PROJECT_SEARCH_RESULTS_POSTS_LINK("//ne-post-results//a[@class='ng-binding']"),
	HOME_PROJECT_COMMENTS_INSERT_LINK_CSS("button[data-cmd='insertLink'] i"),
	HOME_PROJECT_RECORD_COMMENTS_DIV_CSS("div[class='ne-comment-list__comment-content'] div[class^='ne-comment-list__comment-text'] a"),
	RECORD_VIEW_PAGE_COMMENTS_CANCEL_COMMENT_BUTTON_CSS("button[ng-click='vm.cancelCreate()']"), 
	// HOME PAGE
	NEWSFEED_SHAREANIDEA_LINK_XPATH("(//button[@id='posting'])[2]"),
	NEWSFEED_MOST_VIEWED_ARTICLES_XPATH("//ne-most-viewed-documents"),
	NEWSFEED_FEATURED_POST_XPATH("//div[@class='wui-card--featured-post wui-card']"),
	NEWSFEED_TRENDINDING_MENU_XPATH("//ul[@class='nav nav-tabs']//tab-heading[contains(.,'FILTER_TYPE')]"),
	NEWSFEED_TRENDINDING_CATEGORIES_LINKS_XPATH("//ne-trending-categories[@class='ng-isolate-scope']//li"),
	NEWSFEED_TRENDINDING_TOPICS_LINKS_XPATH("//ne-trending-categories[@class='ng-isolate-scope']//li[2]//a"),
	NEWSFEED_RECOMMEND_PEOPLE_XPATH("//ne-recommend-people[@class='ng-scope']"),
	NEWSFEED_RECOMMEND_PEOPLE_LABEL_XPATH("//ne-recommend-people[@class='ng-scope']//div"),
	NEWSFEED_RECOMMEND_PEOPLE_IMAGE_XPATH("//ne-recommend-people[@class='ng-scope ng-isolate-scope']/div//div[@class='horizontal-profiles__image-row']/div"),
	NEWSFEED_RECOMMEND_ARTICLE_XPATH("//ne-recommend-articles[@class='ng-scope ng-isolate-scope']"),
	NEWSFEED_RECOMMEND_ARTICLE_LABEL_XPATH("//ne-recommend-articles[@class='ng-scope ng-isolate-scope']//div"),
	NEWSFEED_RECOMMEND_ARTICLE_A_XPATH("//ne-recommend-articles[@class='ng-scope ng-isolate-scope']//a"),
	NEWSFEED_ALL_NOTIFICATIONS_XPATH("//div[contains(@class,'notification-component')][2]"),
	NEWSFEED_NEW_POST_NOTIFICATIONS_XPATH("//ne-notification-post-creation"),
	NEWSFEED_TRENDINDING_DOCUMENT_TITLES_XPATH("//ul[@class='list-unstyled ne-trending__list']/li/div/div"),
	NEWSFEED_NEW_FOLLOWER_NOTITIFICATION_CSS("ne-notification-new-follower[class='ng-scope ng-isolate-scope'] div"),
	NEWSFEED_NEW_FREND_FOLLOW_NOTITIFICATION_CSS("ne-notify-friend-follows[class='ng-scope'] div"),
	NEWSFEED_TOP_COMMENTERS_XPATH("//div[contains(@ng-if,'TopUserCommenters')]"),
	NEWSFEED_NOTIFICATION_FOLLOWUSER_COMMENT_CSS("div[class='wui-card--comment-event wui-card']"),
	NEWSFEED_NOTIFICATION_FOLLOWUSER_NAME_XPATH("//ne-notification-comment-event[@class='ng-scope ng-isolate-scope']//div[@class='ne-profile-object-name wui-emphasis ng-scope']//a"),
	NEWSFEED_NOTIFICATION_PUBLIC_WATCHLIST_COMMENT_XPATH("//div[@class='wui-card--watchlist-event wui-card']"),
	NEWSFEED_NOTIFICATION_LIKE_POST_XPATH("//ne-notification-like[@class='ng-scope']"),
	NEWSFEED_NOTIFICATION_COMMENT_ON_OWN_POST_XPATH("//ne-notification-document-comment-event[@class='ng-scope']"),

	NEWSFEED_POST_CARD_SECTION_CSS("div[class*='post wui-card']"),
	NEWSFEED_POST_CARD_SECTION_TITLE_CSS("div[class*='wui-card__'] span[class*='ng-scope']"),
	NEWSFEED_POST_CARD_POST_TITLE_CSS("div[class*='wui-content-title']"),
	NEWSFEED_POST_CARD_POST_TITLE_ADD_TO_WATCHLIST_CSS("button[ng-click='WatchButton.openWatchlistSelector()']"),
	NEWSFEED_ARTICLE_CARD_SECTION_CSS("div[class*='articles wui-card']"),
	NEWSFEED_COMMENT_CARD_SECTION_CSS("div[class*='comment-event wui-card']"),

	SEARCH_PAGE_ARTICLES_CSS("a[class='wui-side-menu__link'][ng-click*='ARTICLES']"),
	SEARCH_RESULTS_PAGE_ITEM_CSS("div[class='wui-card__content']"),
	SEARCH_RESULTS_PAGE_ITEM_COMMENTS_COUNT_CSS("div[class*='wui-icon-metric'][tooltip='Comments'] span[class='wui-icon-metric__value ng-binding']"),
	SEARCH_RESULTS_PAGE_ITEM_TITLE_CSS("a[class='ng-binding']"),
	SEARCH_RESULTS_PAGE_POST_TITLE_CSS("a[href^='#/posts']"),
	SEARCH_RESULTS_PAGE_ITEM_TITLE_XPATH("//div[@class='wui-content-title wui-content-title--medium']/a"),
	SEARCH_RESULT_PAGE_SORT_DROPDOWN_CSS("button[id='single-button']"),
	SEARCH_RESULT_PAGE_SORT_LEFT_NAV_PANE_CSS("a[class='wui-side-menu__link']"),
	SEARCH_RESULT_PAGE_POSTS_CSS("a[class='wui-side-menu__link'][ng-click*='POSTS']"),
	SEARCH_RESULT_PAGE_PEOPLE_CSS("a[class='wui-side-menu__link'][ng-click*='PEOPLE']"),
	SEARCH_RESULT_PAGE_ALL_CSS("a[class='wui-side-menu__link'][ng-click*='ALL']"),
	SEARCH_RESULT_PAGE_PATENTS_CSS("a[class='wui-side-menu__link'][ng-click*='PATENTS']"),
	SEARCH_TYPE_AHEAD_ELEMENTS_HEADING_CSS("h4[class='wui-super-header wui-super-header--divider wui-super-header--autocomplete-results'] span"),
	TYPE_AHEAD_SHOWALL_ELEMENTS_CSS("a[class='wui-mini-btn wui-mini-btn--secondary wui-mini-btn--autocomplete-results']"),
	SEARCH_RESULTS_PAGE_ABSTRACTS_CSS("div[class='wui-card__content'] p"),
	SEARCH_RESULTS_PAGE_PROFILE_NAME_LINK_CSS("a[class='ng-binding ng-scope'][event-category='searchresult-ck-profile']"),
	SEARCH_RESULTS_PAGE_PROFILE_DESC_LINK_CSS("div[class='wui-card__body-content'] div[class*='wui-descriptor wui-descriptor__profile']"),
	SEARCH_RESULTS_PAGE_SENDTOENDNOTE_BUTTON_CSS("button[class='wui-icon-btn ng-isolate-scope']"),
	SEARCH_RESULTS_PAGE_LINKIINGMODAl_CLOSE_BUTTON_CSS("button[class='wui-modal__close-btn']"),
	SEARCH_RESULTS_PAGE_LINKIINGMODAl_CSS("div[class='modal-content ng-scope']"),
	SEARCH_RESULTS_PAGE_LINKIINGMODAlTEXT_CSS("div[class='modal-body wui-modal__body'] p"),

	// Added by Chinna on 25th-Oct-2016
	SEARCH_RESULTS_PAGE_ARCTICLE_OR_PATENT_RESULTS_CSS("div[class='wui-card__content'] a"),
	SEARCH_RESULTS_PAGE_ITEM_ADD_TO_GROUP_CSS("div[class*='add-to-group-toggle'] button[ng-click='vm.openProjectSelector()']"),
	SEARCH_RESULTS_PAGE_ITEM_ADD_TO_GROUP_DROPDOWN_CSS("div[class='add-to-group-toggle ng-isolate-scope dropdown open'] div[class='dropdown-menu ne-action-dropdown']"),
	SEARCH_RESULTS_PAGE_ITEM_ADD_TO_GROUP_DROPDOWN_LIST_CSS("div[class='add-to-group-toggle ng-isolate-scope dropdown open'] div[class='dropdown-menu ne-action-dropdown'] ul li"),
	SEARCH_RESULTS_PAGE_RECORDS_TITLE_CSS("div[class='wui-card__header--before-text wui-card__header']"),
	SEARCH_RESULTS_PAGE_DOCUMENT_ADD_TO_GROUP_CSS("button[ng-click='vm.openProjectSelector()']"),
	HOME_PROJECT_NEON_SEARCH_RESULT_PUBLICATION_CSS("ne-search-result-type div[class*='wui-descriptor--uppercase']"),
	HOME_PROJECT_NEON_SEARCH_RESULT_SOURCE_CSS("ne-search-result-type div[class*='wui-descriptor--authors']"),
	HOME_PROJECT_NEON_SEARCH_RESULT_PATENT_PUBLICATION_CSS("ne-search-result-type div[class*='wui-descriptor--uppercase']"),
	HOME_PROJECT_NEON_SEARCH_RESULT_PATENT_SOURCE_CSS("ne-search-result-type div[class='wui-descriptor']"),
	SEARCH_RESULT_PAGE_ADDTOGROUP_DROPDOWN_CSS("div[class^='add-to-group-toggle'][class$='dropdown open'] div[class='dropdown-menu ne-action-dropdown']"),
	// Added by bhavya
	SEARCH_RESULT_PAGE_SORT_DROPDOWN_ITEMS_CSS("SEARCH_RESULT_PAGE_SORT_DROPDOWN_CSS"),
	SEARCH_RESULT_PAGE_RESULTS_LINK_CSS("div[class='wui-card__body-content'] a"),
	SEARCH_RESULT_PAGE_FILTER_LIST_CSS("div[class='panel-heading']"),
	SEARCH_RESULT_PAGE_FILTER_VALUES_CSS("span[class='wui-checkbox__visible']"),
	SEARCH_RECORD_VIEW_PAGE_DETAILS_LINK_CSS("div[class='col-xs-12'] a"),
    SEARCH_RESULT_PAGE_LINKS_CSS("div[class='wui-content-title wui-content-title--medium'] a"),

	// record view page
    RECORD_VIEW_PAGE_COMMENT_DELETE_BUTTON_CSS("button[class='wui-mini-btn wui-mini-btn--secondary'][ng-click='deleteThis(comment.id)']"),
	RECORD_VIEW_PAGE_COMMENT_DELETE_BUTTON1_XPATH("//button[@id='deleting']"),
	RECORD_VIEW_PAGE_COMMENT_DELETE_CONFIMATION_OK_BUTTON_CSS("div[class^='modal-footer'] button[ng-click='vm.close()']"),
	RECORD_VIEW_PAGE_COMMENT_DELETE_CONFIMATION_OK_BUTTON1_XPATH("//button[@class='wui-btn wui-btn--primary' and text()='Delete']"),
	RECORD_VIEW_PAGE_FLAG_REASON_MODAL_CSS("div[class='modal-dialog']"),
	RECORD_VIEW_PAGE_FLAG_REASON_MODAL_CHECKBOX_CSS("span[class='wui-checkbox__visible']"),
	RECORD_VIEW_PAGE_FLAG_REASON_MODAL_CANCEL_BUTTON_CSS("div[class^='modal-footer'] button[ng-click='vm.cancel()']"),
	RECORD_VIEW_PAGE_FLAG_REASON_MODAL_FLAG_BUTTON_CSS("div[class^='modal-footer'] button[ng-click='vm.close()']"),
	RECORD_VIEW_PAGE_COMMENTS_FLAG_BUTTON_CSS("button[ng-click='reportThis()']"),
	RECORD_VIEW_PAGE_COMMENTS_SHOW_MORE_LINK_CSS("button[ng-click='grabMore()']"),
	RECORD_VIEW_PAGE_COMMENTS_EDIT_BUTTON_CSS("button[ng-click='editThis(comment.id)']"),
	RECORD_VIEW_PAGE_COMMENTS_DELETE_BUTTON_CSS("button[ng-click='deleteThis(comment.id)']"),
	RECORD_VIEW_PAGE_COMMENTS_DYNAMIC_XPATH("//div[@class='ne-comment-list__comment-content']"),
	RECORD_VIEW_PAGE_COMMENTS_DYNAMIC_FLAG_XPATH("descendant::button[@ng-click='reportThis()']/i"),
	RECORD_VIEW_PAGE_COMMENTS_TEXTBOX_CSS("div[class='fr-element fr-view']"),
	RECORD_VIEW_PAGE_COMMENTS_TEXTAREA_CSS("textarea[placeholder='Join the discussion']"),
	RECORD_VIEW_PAGE_COMMENTS_ADD_COMMENT_BUTTON_CSS("button[ng-click*='createComment()']"),
	RECORD_VIEW_PAGE_COMMENTS_USER_PROFILE_LINK_XPATH("descendant::div[contains(@class,'ne-user-profile-object-name')]/descendant::a[contains(@href,'#/profile')]"),
	RECORD_VIEW_PAGE_COMMENTS_COUNT_CSS("h3[class*='comment-list'] span"),
	RECORD_VIEW_PAGE_COMMENTS_EDIT_SUBMIT_BUTTON_CSS("button[class='wui-btn wui-btn--primary']"),
	RECORD_VIEW_PAGE_COMMENTS_MATRICS_COUNT_CSS("span[class='wui-icon-metric__value ng-binding']"),
	RECORD_VIEW_PAGE_COMMENTS_BOLD_ICON_CSS("button[data-cmd='bold']"),
	RECORD_VIEW_PAGE_COMMENTS_ITALIC_ICON_CSS("button[data-cmd='italic']"),
	RECORD_VIEW_PAGE_LI_SHARE_MODAL_SHARE_BUTTON_CSS("div[class='modal-footer wui-modal__footer ng-scope'] button[data-ng-click='shareModal.close()']"),
	RECORD_VIEW_PAGE_LI_SHARE_MODAL_CANCEL_BUTTON_CSS("div[class='modal-footer wui-modal__footer ng-scope'] button[data-ng-click='shareModal.cancel()']"),
	RECORD_VIEW_PAGE_COMMENTS_EDIT_CANCEL_BUTTON_CSS("button[ng-click^='cancelEdit']"),
	RECORD_VIEW_PAGE_COMMENTS_EDIT_ERROR_MESSAGE_CSS("div[class=ne-comment-list__comment-content] div[class='wui-textarea__error']"),
	//Commented by KR
	//RECORD_VIEW_PAGE_COMMENTS_EDIT_TEXTBOX_CSS("div[class='ne-comment-list__comment-content'] div[id^='taTextElement']"),
	RECORD_VIEW_PAGE_COMMENTS_EDIT_TEXTBOX_XPATH("div[@class='fr-box fr-basic fr-bottom']/descendant::div[@class='fr-element fr-view']"),
	
	RECORD_VIEW_PAGE_SENDTOENDNOTE_BUTTON_CSS("div[class='ne-publication-sidebar__actions'] div button[class='wui-icon-btn ng-isolate-scope']"),
	RECORD_VIEW_PAGE_SENDTOENDNOTE_TOASTNOTIFICATION_XPATH("//div[@class='message ng-binding']"),
	HOME_PROJECT_NEON_RECORD_VIEW_PUBLICATION_CSS("div[class='ne-publication__header'] div[class='wui-descriptor']"),
	HOME_PROJECT_NEON_RECORD_VIEW_SOURCE_CSS("div[class='ne-publication__header'] div[class*='wui-descriptor--uppercase']"),
	HOME_PROJECT_NEON_RECORD_VIEW_ABSTRACT_CSS("p[class*='ne-publication__body wui-large-text']"),
	HOME_PROJECT_NEON_RECORD_VIEW_METRICS_CSS("div[class='ne-publication-sidebar__metrics'] div[class*='wui-metric']"),
	TRENDING_SECTION_ARTICLE_FROM_NEWSFEED_CSS("a[data-ui-sref='articleView({id:document.id})']"),
	TRENDING_SECTION_POST_FROM_NEWSFEED_CSS("a[data-ui-sref='postsView({id:post.id})']"),
	// login page elements

	LOGIN_PAGE_EMAIL_TEXT_BOX_CSS("input[name='loginEmail']"),
	LOGIN_PAGE_PASSWORD_TEXT_BOX_CSS("input[name='loginPassword']"),
	LOGIN_PAGE_SIGN_IN_BUTTON_CSS("button[class*='wui-btn--login']"),
	LOGIN_PAGE_LOGO_IMG_XPATH("//img[@class='login-logo']"),
	LOGIN_PAGE_CLARIVATE_ANALYTICS_LINK_CSS("div[class='login-splash__container']"),
	CLARIVATE_ANALYTICS_PAGE_CSS("div[id='site-header'] a"),
	SEARCH_RESULTS_PAGE_PEOPLE_TITLE_CSS("div[class='wui-card__content'] a[class='ng-binding ng-scope']"),
	SEARCH_RESULTS_PAGE_POST_AUTHOR_CSS("a[event-category='searchresult-ck-profile'][class='ng-binding ng-scope']"),
	SEARCH_RESULTS_PAGE_POST_AUTHOR_DETAILS_CSS("div[class='ne-user-profile-object-info'] div[class^='wui-descriptor']"),
	WTCHLISH_LINK_XPATH("//span[contains(text(),'Watchlist')]"),
	NEWSFEED_RECOMMENDED_ARTICLES_SECTION_ARTICLE_CSS("div[class='wui-card__line-item']"),
	NEWSFEED_RECOMMENDED_ARTICLE_TITLE_CSS("div[class='wui-content-title ng-binding wui-content-title--small']"),
	ARTICLE_TITLE_IN_RECORD_VIEW_PAGE_CSS("div[class='ne-publication__header'] h2"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_FOLLOW_USER_CSS("div[class='wui-card ng-scope'] span[class='fa fa-check unfollow']"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_NUMBER_OF_USER_CSS("div[class='clearfix horizontal-wrapper'] div[class='ne-user-profile-image-wrapper']"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_COPY_USER_NAME_CSS("span[class='ne-user-profile-object-title'] a"),
	NEWSFEED_RECOMMENDED_ARTICLES_SECTION_XPATH("//div[@class='wui-card--recommended-articles wui-card']"),
	NEWSFEED_RECOMMENDED_ARTICLES_SECTION_ARTICLE_NAME_XPATH("//div[@class='wui-content-title ng-binding wui-content-title--small']"),
	NEWSFEED_RECOMMENDED_ARTICLES_SECTION_WATCHLIST_BUTTON_XPATH("//div[@class='wui-card--recommended-articles wui-card']//button"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_XPATH("//ne-recommend-people[@class='ng-scope ng-isolate-scope']/div"),
	PROFILE_PAGE_AUTOR_NAME_CSS("h2[class='wui-title wui-title--user-profile-name ng-binding']"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_CSS("div[class='wui-card ng-scope']"),
	WATCHLIST_WATCH_BUTTON_CSS("button[class='wui-icon-only-btn ne-action-dropdown__add-button--inactive']"),
	WATCHLIST_WATCH_BUTTON_IN_SEACHPAGE_CSS("span[data-ng-bind='WatchButton.label']"),
	DOCUMENT_TITILE_IN_SEARCHPAGE_XPATH("//div[@class='wui-content-title wui-content-title--medium ng-binding']"),
	DOCUMENT_URL_IN_SEARCHPAGE_XPATH("//ne-post-results[@class='ng-scope ng-isolate-scope']/a"),
	DOCUMENT_TITLE_IN_RECORDVIEW_PAGE_XPATH("//h2[@class='wui-content-title wui-content-title--ne-publication ng-binding']"),
	ADD_COMMENT_BUTTON_XPATH("//button[contains(text(),'Add Comment')]"),
	LOGIN_PAGE_LI_SIGN_IN_BUTTON_CSS("button[class='wui-btn unauth-login-btn li-btn']"),
	LOGIN_PAGE_FB_SIGN_IN_BUTTON_CSS("button[class='wui-btn unauth-login-btn fb-btn']"),
	LOGIN_PAGE_LI_EMAIL_TEXT_BOX_ID("session_key"),
	LOGIN_PAGE_LI_PASSWORD_TEXT_BOX_ID("session_password"),
	LOGIN_PAGE_LI_ALLOW_ACCESS_BUTTON_ID("authorize"),
	LOGIN_PAGE_FB_EMAIL_TEXT_BOX_ID("email"),
	LOGIN_PAGE_FB_PASSWORD_TEXT_BOX_ID("pass"),
	LOGIN_PAGE_FB_LOGIN_BUTTON_ID("loginbutton"),
	FUTUREPOST_AUTHOR_NAME_CSS("div[class='wui-subtitle ne-user-profile-object-title-wrapper'] a"),
	FUTUREPOST_POST_NAME_CSS("div[class='wui-content-title wui-content-title--medium wui-content-title--medium-card-title ng-binding']"),
	FUTUREPOST_WATCHLIST_STATUS_CSS("div[class='wui-card--featured-post wui-card'] button[class='wui-icon-btn wui-icon-btn--horizontal-spacing dropdown-toggle']"),
	FUTUREPOST_WATCHLIST_WATCHING_CSS("button[class='wui-icon-only-btn ne-action-dropdown__add-button--active']"),
	//HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_PUBLISH_XPATH("//div[@class='modal-dialog']/descendant::button[@event-action='publish']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_CANCEL_PUBLISH_XPATH("//button[@class='wui-btn wui-btn--primary ng-binding']"),
	HOME_PROJECT_NEON_PROFILE_CREATE_POST_MODAL_CLOSE_BUTTON_CSS("div[class^='modal-dialog'] button[title='Close']"),
	HOME_PROJECT_NEON_ONBOARDING_MODAL_CSS("div[class='modal-content']"),
	HOME_PROJECT_NEON_ONBOARDING_WELCOME_MODAL_CSS("button[ng-click='$close()']"),
	HOME_PROJECT_NEON_ONBOARDING_WELCOME_MODAL_FEATURE_IMAGES_CSS("div[class*='user-onboarding-modal__feature']"),
	HOME_PROJECT_NEON_ONBOARDING_WELCOME_MODAL_RECOMMENDED_PEOPLE_CSS("div[class='wui-card__content wui-card--borderless__content']"),
	HOME_PROJECT_NEON_ONBOARDING_PROFILE_MODAL_CSS("button[ng-click='UserOnboardingProfile.close()']"),
	HOME_PROJECT_NEON_ONBOARDING_PROFILE_MODAL_CLOSE_CSS("button[ng-click='$dismiss()']"),
	HOME_PROJECT_NEON_ONBOARDING_PROFILE_MODAL_IMAGE_UPLOAD_CSS("ne-user-profile-image[has-image='UserOnboardingProfile.profile.hasImage'] img"),
	HOME_PROJECT_NEON_ONBOARDING_PROFILE_MODAL_IMAGE_EDIT_CSS("button[ng-click='UserImageEditButtons.update()']"),
	HOME_PROJECT_NEON_ONBOARDING_PROFILE_MODAL_IMAGE_DELETE_CSS("button[ng-click='UserImageEditButtons.delete()']"),
	HOME_PROJECT_NEON_SOCIAL_LINKING_ONBOARDING_MODAL_CSS("div[class='modal-content ng-scope'] div[class='wui-input-with-label']"),
	HOME_PROJECT_NEON_SOCIAL_LINKING_ONBOARDING_MODAL_BUTTON_CSS("button[class='wui-btn wui-btn--secondary wui-btn--modal-footer button-color-secondary']"),
	HOME_PROJECT_NEON_STEAMLINKING_WHILE_SENDTOENW_BUTTON_CSS("input[type='password']"),
	HOME_PROJECT_NEON_DIFFSTEAMLINKING_WHILE_SENDTOENW_BUTTON_CSS("button[class='wui-btn wui-btn--secondary button-color-secondary']"),
	HOME_PROJECT_NEON_DIFFSTEAMLINKING_EMAIL_WHILE_SENDTOENW_BUTTON_CSS("input[type='email']"),
	HOME_PROJECT_NEON_DIFFSTEAMLINKING_PWD_WHILE_SENDTOENW_BUTTON_CSS("input[type='password']"),
	HOME_PROJECT_NEON_DIFFSTEAMLINKING_LINKINGMODALTEXT_CSS("div[class='modal-body wui-modal__body'] p"),
	HOME_PROJECT_NEON_INCORRECTPWD_ERRORMSG_CSS("label[class='wui-input-with-label__error']"),
	RECOMMENDED_PEOPLE_SECTION_USER_NAME_XPATH("//ne-recommend-people[@class='ng-scope ng-isolate-scope']/div//span[@class='ne-user-profile-object-title']/a"),
	NEWSFEED_RECOMMENDED_PEOPLE_SECTION_FOLLOW_USER_XPATH("//ne-recommend-people[@class='ng-scope ng-isolate-scope']/div//span[@class='fa fa-check unfollow']"),
	SEARCH_RESULTS_PAGE_CSS("h2[class='wui-title']"),
	ENW_HOME_AGREE_CSS("input[title='I Agree']"),
	ENW_HOME_CONTINUE_XPATH("//div[@id='continue']"),
	ENW_HOME_PROFILE_IMAGE_XPATH("//img[@id='proSmallImg']"),
	ENW_HOME_HEADER_NEON_PLINK("Project Neon"),
	ENW_HOME_PROFILE_FLYOUT_HEADER_CSS("li[class='dropdown-header'] a"),
	ENW_HOME_PROFILE_FLYOUT_LINKS_CSS("li[class='profilelinks']"),
	ENW_HOME_PROFILE_FLYOUT_ACCOUNT_LINK("Account"),
	ENW_HOME_PROFILE_FLYOUT_FEEDBACK_LINK("Feedback"),
	ENW_HOME_PROFILE_FLYOUT_SIGNOUT_LINK("Sign out"),
	NEON_TO_ENW_BACKTOENDNOTE_LINK("< Back to EndNote"),
	NEON_TO_ENW_PLINK("EndNote"),
	NEON_TO_ENW_BACKTOENDNOTE_PAGELOAD_CSS("div[class='wui-spinner__circle wui-spinner__circle--delayed']"),
	HOME_PROJECT_NEON_ONBOARDING_WELCOME_MODAL_TEXT_CSS("div[class^='modal-header wui-modal__header']"),
	ENDNOTE_LOGIN_AGREE_BUTTON_CSS("input[class='button-form btn-common']"),
	ENDNOTE_LOGIN_CONTINUE_BUTTON_CSS("div[class='btn-common']"),
	ENDNOTE_LOGOUT_HEADER_LABLE_XPATH("(//a[@class='dropdown-toggle'])[2]"),
	ENDNOTE_LOGOUT_SIGNOUT_LINK_XPATH("(//a[contains(text(),'Sign out')]"),
	ENDNOTE_ACCOUNT_LINK_XPATH("//span[@class='fa fa-cog profile_account_link']"),
	ENDNOTE_ACCOUNT_PAGE_PREFERENCE_LINK_XPATH("//div[@class='elqHeading']"),
	ENDNOTE_ACCESS_CENTER_EMAIL_FIELD_CSS("input[class='elqField']"),
	ENDNOTE_ACCESS_CENTER_SUBMIT_BUTTON_CSS("input[id='submit']"),
	ENDNOTE_ACCESS_CENTER_VERIFICATION_MAIL_CSS("div[class='elqHeading']"),
	ENDNOTE_RESET_PASSWORD_PAGE_CSS("div[class='forgot-password-header'] h3"),
	SINGIN_USING_LINKEDIN_CSS("button[class='wui-btn wui-btn--secondary wui-btn--modal-footer button-color-secondary ng-binding']"),
	ACCOUNT_PAGE_LINKEDIN_MAIL_XPATH("(//div[@class='account-option-item ng-scope']/div[@class='account-option-item__text-container']/span)[1]"),
	LINKED_STEAM_ACCOUNT_XPATH("(//div[@class='account-option-item ng-scope']/div[@class='account-option-item__text-container']/span)[2]"),
	LINK_ACCOUNT_BUTTON_ACCOUNT_PAGE_XPATH("//button[@class='wui-btn wui-btn--secondary']"),
	LOCKED__XPATH("(//label[contains(text(),'Make primary')])[1]"),
	LOCKED_MSG_XPATH("//h2[contains(text(),'Your account has been locked.')]"),
	LOCKED_OK_BUTTON_XPATH("//button[@class='wui-btn wui-btn--secondary button-color-secondary']"),

	// Navigation and Landing page
	NEON_ENW_INTEGRATION_TEXT_CSS("p[class='sign-in-options-text text-center']"),
	NEON_ENW_COMPANY_CSS("h4[class='wui-title login-header__app-name ng-binding']"),
	BRANDING_NAME_CSS("img[alt='Clarivate Logo']"),
	NEON_MARKETING_COPY_CSS("h3[class$='app-name ng-binding']"),
	NEON_CONNECT_ICON_CSS("i[class='fa fa-users login-splash-icon']"),
	ENW_SHIBB_LINK_CSS("a[class='shibboleth-link']"),
	ENW_DESKTOP_TEXT_CSS("h5[class='endnote-advertisement__header']"),
	ENW_DESKTOP_DOWNLOAD_LINK("Download"),
	MATCHING_STEAM_MODALTITLE_CSS("h3[class='wui-modal__title']"),
	ENWLANDINGPAGE_FIND_ICON_CSS("i[class='fa fa-search login-splash-icon']"),
	ENWLANDINGPAGE_CREATE_ICON_CSS("i[class='fa fa-file-text login-splash-icon']"),
	ENWLANDINGPAGE_ORGANIZE_ICON_CSS("i[class='fa fa-cloud login-splash-icon']"),
	ACCOUNT_NOTACTIVATED_MSG_XPATH("//h3[@class='wui-modal__title' and contains(.,'Your account registration')]"),
	OK_BUTTON_ACCOUNT_NOTACTIVATED_XPATH("//button[@class='wui-btn wui-btn--secondary button-color-secondary' and contains(.,'OK')]"),
	OK_BUTTON_CSS("button[class^='wui-btn wui-btn--secondary']"),
	NO_LETS_CONTINUE_BUTTON_XPATH("//button[contains(text(),'continue')]"),
	SIGNIN_USING_FB_BUTTON_CSS("button[ng-click='vm.callSocialLogin()']"),
	PROFILENAME_CSS("a[class='ng-binding ng-scope']"),
	NOT_NOW_BUTTON_CSS("a[event-action*='skip-linking']"),
	CONTACT_CUSTOMER_SUPPORT_TITLE_CSS("h2[class='login-title']"),
	CONTACT_CUSTOMER_SUPPORT_MSG_XPATH("//div[@class='col-xs-10 col-xs-offset-1 text-center']/p"),
	ENDNOTE_LOGO_CSS("a[title='EndNote logo']"),
	DID_YOU_KNOW_MODAL_STEAMPW_CSS("input[name='steamPassword']"),
	PROFILE_PAGE_WATCHLIST_COUNT_XPATH("//a[@data-event-category='profilewatchlists']/span[@class='wui-side-menu__badge ng-binding']"),
	ALREADY_HAVE_AN_ACCOUNT_NOTNOW_CSS("div[class='modal-content ng-scope']"),
	HOME_PROJECT_NEON_HEADER_CSS("a[class='ne-logo__link']"),

	// AccountSettingPage
	ACCOUNT_RADIOBUTTON1_XPATH("(//label[contains(text(),'Make primary')])[1]"),
	ACCOUNT_RADIOBUTTON2_XPATH("(//label[contains(text(),'Make primary')])[2]"),
	HEADER_LABEL_XPATH("(//div[@class='ne-user-profile-image-main-wrapper'])[1]"),
	ACCOUNT_LINK_CSS("a[data-ui-sref='account.settings']"),
	ACCOUNT_ACTUAL_EMAIL_XPATH("//div[@class='account-option-item ng-scope']//span[@class='ng-binding']"),
	ACCOUNT_ACTUAL_EMAIL1_XPATH("//div[@class='account-content']/div[3]/div/span"),
	ACCOUNT_LINK_BUTTON_XPATH("//button[@class='wui-btn wui-btn--secondary']"),
	LINK_LOGIN_NAME("email"),
	DONE_BUTTON_CLICK_XPATH("//button[@class='wui-btn wui-btn--secondary wui-btn--modal-footer button-color-secondary']"),
	ACCOUNT_TEXT_COMPARE_XPATH("//p[@ng-show='Account.showEmailNotifications()']"),
	ACCOUNT_TEXT_COMPARE_AFTERLINK_XPATH("//div[@class='col-xs-12']/p"),
	ACCOUNT_TEXT_COMPARE_SELECTPRIMARY_XPATH("//p[@ng-show='Account.hasMultipleAccounts']"),
	ACCOUNT_TEXT_COMPARE_PASSWORD_XPATH("//div[@class='account-option-item__text-container']/h6[2]"),
	ACCOUNT_LINKEDIN_ICON_XPATH("//i[@class='fa fa-linkedin-square account-option-item__icon-linkedin']"),
	ACCOUNT_fACEBOOK_ICON_XPATH("//i[@class='fa fa-facebook-square account-option-item__icon-facebook']"),
	ACCOUNT_STEAM_ICON_XPATH("//i[@class='fa fa-envelope-o account-option-item__icon-steam']"),
	TEXT_ACCOUNTPAGE_XPATH("//div[@ng-hide='Account.isSteamProvider()']/p"),
	TEXT_ACCOUNTPAGE1_XPATH("//p[contains(text(),'Project Neon has linked your accounts. You can sign in with any of the accounts you already use.')]"),
	ACCOUNT_CHANGE_PASSWORD_LINK_CSS("h6[class='account-option-item__text-sub ng-scope'] a"),
	EMAIL_BODY_PASSWORD_RESET_LINK_CSS("[class='email_body'] a"),
	NEON_LANDING_PAGE_LOGGIN_BANNER_CSS("div[class='login-body']"),
	ACCOUNT_PAGE_EMAIL_PREFERENCE_LINK_CSS("a[class='wui-btn wui-btn--secondary']"),
	NEON_HELP_AND_FEEDBACK_LINK_CSS("a[data-event-action='help-feedback']"),
	NEON_HELP_AND_FEEDBACK_PAGE_SEND_FEEDBACK_LINK_CSS("a[class='feedback-link__anchor ng-binding']"),
	NEON_HELP_AND_FEEDBACK_PAGE_SUBMIT_SUPPORT_LINK_CSS("a[class='feedback-link__anchor']"),
	NEON_ACCOUNT_PAGE_USER_NAME_CSS("div[class='account-option-item__text-container'] span"),
	ENW_NOTNOW_XPATH("//a[@ng-click='vm.callSkipLinking()']"),
	ENW_PROFILE_HEADER_XPATH("//span[@class='ne-nav-logo__text ne-nav-logo__text--tr']"),
	NEON_PROFILE_HEADER_XPATH("//span[@class='ne-logo__text ne-logo__text--tr']"),
	ENW_STEAM_PASSWORD_XPATH("//input[@class='wui-input-with-label__input ng-pristine ng-untouched ng-invalid ng-invalid-required']"),
	NEON_OK_BUTTON_XPATH("//a[@class='ng-binding ng-scope']"),

	// #######RCC#############
	RCC_GROUP_GROUPTAB_HEADER_XPATH("//a[contains(.,'Groups')]"),
	RCC_GROUP_CREATE_NEW_GROUP_BUTTON_CSS("button[class*='wui-icon-btn--add-group']"),
	RCC_GROUP_GROUPS_COUNT_CSS("a[href*='groups'] span[class*='wui-side-menu__badge']"),
	RCC_GROUP_INVITATIONS_COUNT_CSS("a[href*='invites'] span[class*='wui-side-menu__badge']"),
	RCC_GROUPSLIST_ENTER_GROUP_TILTLE_CSS("div[class='research-group-card__content'] input[name='name']"),
	RCC_GROUPSLIST_ENTER_GROUP_DESCRIPTION_CSS("div[class='research-group-card__content'] textarea[placeholder*='Give your group a description']"),
	RCC_GROUPSLIST_SAVE_GROUP_BUTTON_CSS("div[class='research-group-card__content'] button[type='submit']"),
	RCC_GROUPSLIST_CANCEL_GROUP_BUTTON_CSS("div[class='research-group-card__content'] button[ng-click='vm.revert()'"),
	RCC_GROUPSLIST_GROUP_CARD_CSS("div[class='wui-card__content']"),
	RCC_GROUPSLIST_GROUP_TITLE_CSS("a[class='research-group-card__text']"),
	RCC_GROUPDETAILS_ARTICLES_COUNT_CSS("a[ui-sref='groups.details.articles'] span"),
	RCC_GROUPDETAILS_PATENTS_COUNT_CSS("a[ui-sref='groups.details.patents'] span"),
	RCC_GROUPDETAILS_POSTS_COUNT_CSS("a[ui-sref='groups.details.posts'] span"),
	RCC_GROUPDETAILS_ATTACHED_FILES_COUNT_CSS("a[ui-sref='groups.details.linked-items'] span"),
	RCC_GROUPDETAILS_MEMBERS_COUNT_CSS("a[ui-sref='groups.details.members.list'] span"),
	RCC_GROUPSDETAILS_DELETE_GROUP_BUTTON_CSS("div[class^='research-group-card__footer'] button[ng-click*='group.delete()']"),
	RCC_GROUPSDETAILS_EDIT_GROUP_BUTTON_CSS("div[class^='research-group-card__footer'] button[ng-click*='vm.edit()']"),
	RCC_GROUPSDETAILS_ATTACH_FILE_BUTTON_CSS("div[class^='research-group-card__footer'] button[ng-click*='Attach.attachDriveDocument()']"),
	RCC_GROUPSDETAILS_INVITE_OTHERS_BUTTON_CSS("div[class^='research-group-card__footer'] a"),
	RCC_GROUPDETAILS_MEMBERS_TAB_CSS("a[class='wui-side-menu__link'][ui-sref='groups.details.members.list']"),
	RCC_GROUPDETAILS_ATTACHED_FILES_TAB_CSS("a[class='wui-side-menu__link'][ui-sref='groups.details.linked-items']"),
	RCC_GROUPDETAILS_POSTS_TAB_CSS("a[class='wui-side-menu__link'][ui-sref='groups.details.posts']"),
	RCC_GROUPDETAILS_PATENTS_TAB_CSS("a[class='wui-side-menu__link'][ui-sref='groups.details.patents']"),
	RCC_GROUPDETAILS_ARTICLES_TAB_CSS("a[class='wui-side-menu__link'][ui-sref='groups.details.articles']"),
	RCC_GROUPDETAILS_GROUP_TITLE_CSS("div[class='research-group-card__text'] div[class*='wui-content-title']"),
	RCC_GROUPSLIST_GROUP_TITLE_LINK_CSS("a[class='research-group-card__text'] div[class*='wui-content-title']"),
	RCC_GROUPDETAILS_INVITE_MEMBER_TYPE_AHEAD_CSS("div[class='wui-card__content'] input"),
	RCC_GROUPDETAILS_INVITE_MEMBER_TYPE_AHEAD_OPTIONS_CSS("ul[class='suggestion-list'] li span[class='ng-binding ng-scope']"),
	RCC_GROUPDETAILS_INVITE_MEMBERS_SEND_BUTTON_CSS("button[event-action='save']"),
	RCC_GROUPDETAILS_INVITE_MEMBERS_CANCEL_BUTTON_CSS(""),
	RCC_GROUPDETAILS_PENDING_MEMBERS_NAMES_CSS("group-pending-invite div[class='wui-card__content'] a[class='ng-binding ng-scope']"),
	RCC_GROUPDETAILS_PENDING_MEMBERS_CANCEL_INVITATION_BUTTON_CSS("button[class='wui-icon-btn']"),
	RCC_GROUPINVITATIONS_INVITATION_CARD_CSS("div[class='wui-card__content']"),
	RCC_GROUPINVITATIONSFULL_INVITATION_CARD_CSS("div[class='wui-card']"),
	RCC_GROUPINVITATIONS_INVITATION_CARD_TITLE_CSS("div[class='wui-title wui-content-title--medium ng-binding ng-scope']"),
	RCC_GROUPINVITATIONS_DECLINE_INVITAION_BUTTON_CSS("button[class^='wui-btn wui-btn--secondary']"),
	RCC_GROUPINVITATIONS_ACCEPT_INVITAION_BUTTON_CSS("button[class^='wui-btn wui-btn--primary']"),
	RCC_GROUPINVITATIONS_GROUP_DETAILS_BUTTON_CSS("div[class='group-card-item wui-card__body-content'] i"),
	RCC_GROUPSLIST_GROUP_ITEMS_COUNT_CSS("div[class='ng-isolate-scope wui-metric'][labels*='Items']"),
	RCC_GROUPSLIST_GROUP_MEMBERS_COUNT_CSS("div[class='ng-isolate-scope wui-metric'][labels*='Members']"),
	RCC_GROUPSLIST_GROUP_DESCRIPTION_CSS("a[class='research-group-card__text'] p"),
	RCC_GROUP_GROUPS_LINK__CSS("span[class='wui-title'] a"),
	RCC_GROUPSLIST_GROUP_OWNER_NAME_CSS("div[class='research-group-card__content'] div[class='ne-user-profile-object-info'] a[event-category*='ck-profile']"),
	RCC_GROUPSLIST_GROUP_OWNER_ROLE_CSS("div[class='ne-user-profile-object-info'] div[class*='wui-descriptor__profile']"),
	RCC_GROUPDETAILS_DELETE_CONFIMATION_DELETE_BUTTON_CSS("div[class='modal-dialog ng-scope'] button[event-action='delete']"),
	RCC_GROUPINVITATIONS_CUSTOM_MESSAGE_CSS("textarea[name='inviteMessage']"),
	RCC_GROUPDETAILS_INVITATION_CUSTOM_MESSAGE_CSS("div[class='wui-card__body-content'] span[class='ng-binding ng-scope']"),
	RCC_GROUPINVITATIONS_FOLLOW_OWNER_CSS("button[class*='ne-user-follow-unfollow']"),
	RCC_GROUP_INIVATIONS_DETAILS_DISC_CSS("div[class='project-invite-description ng-binding ng-scope']"),
	RCC_GROUP_INVITATIONS_DETAILS_TIMESTAMP_XPATH("preceding-sibling::div[@class='wui-card__label-header']"),

	RCC_GROUP_SORT_CSS("button[id='rcc-sort-groups'] span:nth-child(1)"),
	RCC_INVITATION_MESSAGE1_CSS("groups-invites-directive div[class='ng-scope'] span[class^='wui-title wui-emphasis']"),
	RCC_INVITATION_MESSAGE2_CSS("groups-invites-directive div[class='ng-scope'] span[class='rcc-no-items-text']"),

	RCC_GROUPS_MESSAGE1_CSS("groups-list-directive div[class='ng-scope'] span[class^='wui-title wui-emphasis']"),
	RCC_GROUPS_MESSAGE2_CSS("groups-list-directive div[class='ng-scope'] span[class='rcc-no-items-text']"),
	RCC_INVITATIONLINK_CSS("li[class*='wui-side-menu__list-item'] a[href*='invites']"),
	RCC_GROUPLINK_CSS("li[class*='wui-side-menu__list-item'] a[href*='groups']"),
	RCC_GROUPS_DETAILS_CONFIRMATION_MODAL_CSS("div[class='modal-dialog ng-scope']"),
	RCC_GROUPS_DETAILS_CONFIRMATION_MODAL_CANCEL_BUTTON_CSS("div[class='modal-content'] button[class='wui-btn wui-btn--secondary']"),
	RCC_GROUPS_DETAILS_CONFIRMATION_MODAL_CLOSE_BUTTON_CSS("div[class='modal-content'] button[class='wui-modal__close-btn']"),
	RCC_GROUPS_DETAILS_CONFIRMATION_MODAL_SUBMIT_BUTTON_CSS("div[class='modal-content'] button[class='wui-btn wui-btn--primary ng-binding']"),

	RCC_GROUPDETAILS_ARTICLES_TAB_DETAILS_CSS("div[class='wui-card__content'] a[event-category='rcc-group-ck-wos']"),
	RCC_GROUPDETAILS_PATENTS_TAB_DETAILS_CSS("div[class='wui-card__content'] a[event-category='rcc-group-ck-patents']"),
	RCC_GROUPDETAILS_POSTS_TAB_DETAILS_CSS("div[class='wui-card__content'] a[event-category='rcc-group-ck-posts']"),
	RCC_GROUPDETAILS_PENDING_MEMBERS_CARD_CSS("group-pending-invite div[class='wui-card__content']"),

	RCC_GROUPINVITATIONS_GROUP_OWNER_NAME_CSS("div[class='ne-user-profile-object-info'] a[event-category*='ck-profile']"),
	RCC_GROUPINVITATIONS_GROUP_OWNER_ROLE_CSS("div[class='ne-user-profile-object-info'] div[class*='wui-descriptor__profile']"),
	RCC_GROUPDETAILS_GROUP_OWNER_NAME_CSS("div[class='research-group-card__content'] div[class='ne-user-profile-object-info'] a"),
	RCC_GROUPDETAILS_GROUP_OWNER_ROLE_CSS("div[class='research-group-card__content'] div[class*='wui-descriptor wui-descriptor__profile']"),
	RCC_GROUPDETAILS_GROUP_DESCRIPTION_CSS("div[class='research-group-card__text'] p[class*='wui-content-title']"),
	RCC_COUNT_GROUP_OVERLAY_CSS("span[class^='groups-link-invites']"),
	RCC_COUNT_GROUP_AND_INVITATIONS_CSS("span[class='wui-side-menu__badge ng-binding']"),
	RCC_DEFAULT_SELECTED_INVITATION_TAB_CSS("li[class='wui-side-menu__list-item wui-side-menu__list-item--active']"),
	RCC_DEFAULT_SELECTED_INVITATION_TAB_TEXT_CSS("li[class='wui-side-menu__list-item wui-side-menu__list-item--active'] a"),
	RCC_GROUP_TITLE_CSS("div[class='wui-content-title--medium wui-content-title--medium wui-content-title--medium-spacing ng-binding']"),
	RCC_GROUP_DETAILS_PAGE_PENDING_INVITATION_MESSAGE_CSS("div[class='ng-binding ng-scope']"),
	RCC_GROUP_DETAILS_PAGE_INFO_TEXT_CONFIRMATION_MODAL_CSS("div[class='modal-body wui-modal__body'] p"),
	RCC_GROUP_DETAILS_PAGE_LABEL_TEXT_CONFIRMATION_MODAL_CSS("h3[class='wui-modal__title ng-binding']"),
	RCC_GROUP_DETAILS_PAGE_PENDING_INV_MSG_CSS("h3[class='wui-title wui-title--invite-spacing-large']"),
	RCC_GROUPLIST_LEAVE_GROUP_BUTTON_CSS("button[class='wui-mini-btn wui-mini-btn--secondary wui-mini-btn--research-card']"),
	RCC_GROUPLIST_LEAVE_GROUP_POP_VERIFICATION_TEXT_CSS("div[class='modal-body wui-modal__body']"),
	RCC_GROUPLIST_LEAVE_GROUP_POP_UP_CANCEL_BUTTON_CSS("div[class='modal-footer wui-modal__footer'] button[class='wui-btn wui-btn--secondary']"),
	RCC_GROUPLIST_LEAVE_GROUP_POP_UP_LEAVEGROUP_BUTTON_CSS("div[class='modal-footer wui-modal__footer'] button[class='wui-btn wui-btn--primary ng-binding']"),
	RCC_GROUPLIST_LEAVE_GROUP_POP_UP_CLOSE_BUTTON_CSS("div[class='modal-header wui-modal__header'] button[class='wui-modal__close-btn']"),
	RCC_GROUP_LIST_PAGE_ADDED_USER_DETAILS_CSS("div[class='wui-card__body-content']"),
	RCC_GROUPDETAILS_MEMBERS_CARD_CSS("group-member div[class='wui-card__content']"),
	RCC_GROUPDETAILS_MEMBERS_NAME_CSS("group-member div[class='wui-card__content'] a[class='ng-binding ng-scope']"),
	RCC_GROUPDETAILS_MEMBERS_REMOVE_BUTTON_CSS("button[class='wui-btn wui-btn--secondary']"),
	RCC_GROUP_DETAILS_PAGE_MEM_LIST_MSG_CSS("h3[class='wui-title wui-title--rcc-spacing']"),
	RCC_GROUPDETAILS_PATENT_RECORD_CARD_CSS("group-patent-item div[class='wui-card__content']"),
	RCC_GROUPDETAILS_POST_RECORD_CARD_CSS("group-post-item div[class='wui-card__content']"),
	RCC_GROUPDETAILS_ARTICLE_RECORD_CARD_CSS("group-article-item div[class='wui-card__content']"),
	RCC_GROUPDETAILS_RECORD_CARD_TITLE_CSS("div[class*='wui-content-title'] a"),
	RCC_GROUPDETAILS_RECORD_CARD_REMOVE_BUTTON_CSS("div[class='wui-card__footer-content'] button[class*='delete-group-item']"),
	RCC_GROUPDETAILS_RECORD_CARD_ATTACHFILE_BUTTON_CSS("div[class='wui-card__footer-content'] button[ng-click*='attachDriveDocument']"),
	RCC_GROUPDETAILS_RECORD_PUBLICATION_AUTHORS_CSS("div[class*=' ne-publication-authors']>span"),
	RCC_GROUPDETAILS_RECORD_SOURCE_CSS("div[class*='wui-descriptor--article-source']"),
	RCC_GROUPDETAILS_RECORD_ABSTRACT_CSS("p[class*='ne-user-comment-text']"),
	RCC_GROUPS_DETAILS_NO_RECORDS_INFO_TEXT_CSS("div[class='ng-binding ng-scope']"),
	RCC_GROUPDETAILS_RECORD_PUBLICATION_METRICS_XPATH("//div[contains(@class,'ne-publication-authors')]/descendant::*[@class='wui-metric' or @class='wui-icon-metric'or @class='pull-right wui-icon-metric']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_DIV_CSS("attached-document"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_TTILE_CSS("*[class^='gdrive-doc__title']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_DESC_CSS("div[ng-show*='Doc.model.desc']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_EDIT_TITLE_CSS("input[class^='edit-form-name-input']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_EDIT_DESC_CSS("textarea[class^='edit-form-description-textarea']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_CANCEL_BUTTON_CSS("button[event-action='cancel']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_UPDATE_BUTTON_CSS("button[event-action='save']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_ITEM_LEVEL_TIMESTAMP_CSS("div[class='gdrive-doc__header'] span[class*='wui-descriptor']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_LINK_CSS("a[class^='open-drive-doc']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_EDIT_BUTTON_CSS("button[ng-click='Doc.toggleEditForm()']"),
	RCC_GROUPDETAILS_RECORD_GOOGLE_DOC_REMOVE_BUTTON_CSS("button[ng-click='Doc.removeDocument()']"),
	RCC_GROUPDETAILS_GOOGLE_DOC_TITLE_XPATH("//span[contains(.,'TITLE')]"),
	RCC_GROUPDETAILS_GOOGLE_DOC_SELECT_XPATH("//div[contains(.,'Select') and @role='button']"),

	RCC_GROUP_BUTTON_XPATH("//span[contains(text(),'Groups')]"),
	RCC_NEW_GROUP_BUTTON__CLICK_XPATH("//button[@class='wui-icon-btn wui-icon-btn--add-group']"),
	RCC_ENTER_TEXT_XPATH("//div[@class='research-group-card__content']//input[@name='name']"),
	RCC_ERROR_MSG_TEXT_XPATH("//label[@class='wui-input__error ng-scope']"),
	RCC_DESC_MSG_TEXT_XPATH("(//div [@class='wui-content-title wui-content-title--research-card-title ng-binding'])[1]"),
	RCC_GROUP_DETAIL_PAGE_SUPPORT_LINK_CSS("p[ng-show='vm.linkItems']"),
	RCC_GROUP_DETAILS_PAGE_SHARE_LINK_CSS("div[class='research-group-card__content'] i[class='research-group-card__icon fa fa-users']"),
	RCC_RECORD_VIEW_PAGE_USER_DETAILS_CSS("div[class='wui-descriptor wui-descriptor--user-profile-details'] span"),

	RCC_GROUP_DETAILS_PAGE_GROUP_TITLE_TEXT_CSS("div[class='research-group-card__text'] div"),
	RCC_GROUP_DETAILS_PAGE_GROUP_DESC_TEXT_CSS("div[class='research-group-card__text'] p"),

	RCC_INVITEMEMBERS_CANCEL_BUTTON_CSS("button[event-action='cancel']"),
	RCC_INVITEMEMBERS_SEND_BUTTON_CSS("button[event-action='save']"),
	RCC_INVITEMEMBERS_TEXTFIELD_CSS("div[class='tags'] input"),
	RCC_INVITEMEMBERS_ENTERED_TEXTFIELD_CSS("div[class='tags'] span"),
	RCC_INVITEMEMBERS_ERRORMESSAGE_CSS("div[class='invitation-error']"),
	RCC_PENDING_INVITATIONS_MESSAGE_CSS("div[class='ng-binding ng-scope']"),
	RCC_INVITATIONS_STATUS_CSS("div[class='pull-right ng-binding ng-scope']"),
	RCC_INVITATION_DESCRIPTION_CSS("textarea[placeholder='Add a description']"),

	RCC_GROUP_LIST_PAGE_GROUP_SORT_BY_MENU_CSS("ul[class='dropdown-menu search-sort-dropdown__menu'] li"),
	RCC_GROUP_LIST_PAGE_SORT_BUTTON_CSS("button[id='rcc-sort-groups']"),
	RCC_GROUP_LIST_PAGE_TITLE_CSS("a[class='research-group-card__text'] div"),
	RCC_GROUP_LIST_PAGE_GROUPS_TILE_DATE_CSS("span[class='ng-binding ng-scope']"),

	RCC_GROUP_LIST_PAGE_GROUP_CARD_CSS("div[ui-view='createGroup']"),
	RCC_GROUP_LIST_PAGE_GROUP_CARD_CANCEL_BUTTON_CSS("div[ui-view='createGroup'] div[class='research-group-card__buttons'] button"),
	RCC_SAVE_BUTTON_XPATH("//button [@class='wui-mini-btn wui-mini-btn--primary wui-mini-btn--research-card']"),
	RCC_GROUPDETAILS_DESCRIPTION_XPATH("//p[@class='research-group-card__description ng-binding']"),
	RCC_GROUP_DESCRIPTION_XPATH("(//p[@class='research-group-card__description ng-binding'])[1]"),
	RCC_GROUPSDETAILS_CANCEL_GROUP_BUTTON_CSS("div[class='research-group-card__buttons'] button[ng-click='vm.revert()']"),
	RCC_VIEW_MODE_CSS("p[ng-show='vm.linkItems']"),
	RCC_TITLE_MSG_TEXT_XPATH("//div [@class='wui-content-title wui-content-title--research-card-title ng-binding']"),

	RCC_GROUP_COVER_PHOTO_CSS("div[class^='responsive-image__placeholder-text']"),
	RCC_GROUP_COVER_UPDATE_PHOTO_CSS("div >ne-responsive-image > div > div > button[class = 'wui-btn wui-btn--primary']"),
	RCC_NEWLY_CREATED_GROUP_PHOTO_CSS("div[class='responsive-image__image ng-scope']"),
	RCC_GROUPDETAILS_RECORD_GROUP_LEVEL_GOOGLE_DOC_TIMESTAMP_CSS("div[class='wui-card__label-header']"),

	RCC_GROUPLIST_DELETE_GROUP_POP_VERIFICATION_TEXT_CSS("div[class='modal-body wui-modal__body']"),
	RCC_GROUPLIST_DELETE_GROUP_POP_UP_CANCEL_BUTTON_CSS("div[class='modal-footer wui-modal__footer'] button[class='wui-btn wui-btn--secondary']"),
	RCC_TOTAL_GROUP_COUNT("li[class='wui-side-menu__list-item wui-side-menu__list-item--active'] span[class='wui-side-menu__badge ng-binding']"),
	GROUPLIST_DELETE_GROUP_POP_UP_DELETEGROUP_BUTTON_CSS("button[class='wui-btn wui-btn--primary ng-binding']"),
	RCC_GROUPLIST_DELETE_GROUP_POP_UP_DELETEGROUP_BUTTON_CSS("div[class='modal-footer wui-modal__footer'] button[class='wui-btn wui-btn--primary ng-binding']"),
	RCC_SRARCHLIST_ARTICLE_CREATE_GROUP_CSS("input[placeholder='Create a new group']"),
	RCC_SEARCH_LIST_ARTICLE_CREATE_GROUP_BUTTON_CSS("button[ng-click='vm.createProject()']"),
	RCC_SEARCH_LIST_CREATED_GROUP_ICON("button[class='wui-icon-only-btn ne-action-dropdown__add-button--active']"),
	RCC_SEARCH_LIST_VERIFY_GROUPNAME("a[class='ne-action-dropdown__item-content']"),
	RCC_SEARCH_LIST_ADD_ARTICLE_ADD_GROUP_ICON("button[class='wui-icon-only-btn ne-action-dropdown__add-button--active']"),
	RCC_SRARCHLIST_ARTICLE_CREATE_GROUP_SPINNER_CSS("div[class^='wui-spinner'] div[class='wui-spinner__circle wui-spinner__circle--delayed']"),

	RCC_GMAIL_LOGIN_USERNAME_ID("Email"),
    RCC_GMAIL_LOGIN_NEXT_BUTTON_XPATH("//input[@id='next']"),
    RCC_GMAIL_LOGIN_SUBMIT_XPATH("//input[@id='signIn']"),
    RCC_GMAIL_LOGIN_PASSWORD_XPATH("//input[@id='Passwd']"),
    RCC_GMAIL_CLICK_EMAIL_XPATH("//span[@class='y2']"),

    RCC_CLICK_ON_GMAIL_SECURITY_LINK_XPATH("//a[@class='WaidBe']"),
    RCC_GMAIL_SUBJECT_CONTENT_XPATH("//h2[@class='hP']"),
    RCC_GMAIL_WHOLE_CONTENT_CSS("table[class*='container']"),
    RCC_GMAIL_WHOLE_CONTENT2_CSS("div[class='nH aHU']"),
    RCC_GMAIL_PROFILE_CLICK_CSS("span[class='gb_9a gbii']"),
    RCC_GMAIL_LOGOUT_BUTTON_CSS("a[id='gb_71']"),
    RCC_GMAIL_SWITCH_TO_ACCOUNT_GOOGLE_XPATH("//button[@class='jfk-button jfk-button-standard']"),
    RCC_GMAIL_CLICK_CONTINUE_XPATH("//input[@type='submit']"),   

	// #################### DRA ##########################
    DRA_LOGO_CSS("h3[class='wui-title wui-title--app-signin-secondaryname']"),
	DRA_BRANDING_NAME_CSS("h2[class='wui-title wui-title--app-signin-primaryname']"),
	DRA_LANDINGPAGE_EXPLORE_ICON_CSS("i[class='fa fa-compass login-splash-icon']"),
	DRA_LANDINGPAGE_IDENTIFY_ICON_CSS("i[class^='wui-icon wui-icon--target-point']"),
	DRA_LANDINGPAGE_VALIDATE_ICON_CSS("i[class='fa fa-check-circle-o login-splash-icon']"),
	DRA_LANDINGPAGE_RANK_ICON_CSS("i[class='fa fa-signal login-splash-icon']"),
	DRA_LANDINGPAGE_TERMS_LINK_CSS("a[data-event-action='login-terms-of-use']"),
	DRA_LANDINGPAGE_PRIVACY_LINK_CSS("a[data-event-action='login-privacy-statement']"),
    DRA_LANDINGPAGE_HELP_MESSAGE_CSS("p[class='tos ng-scope']"), 
	DRA_LANDINGPAGE_SUPPORT_MAILID_CSS("p[class='tos ng-scope'] >a[event-action='login-customer-care-dra']"),
	DRA_LANDINGPAGE_LEARNMORE_LINK_CSS("span[class='splash-announcement-link__text']"),
	DRA_LINKINGMODAL_FB_SIGN_IN_BUTTON_CSS("button[class^='wui-btn wui-btn--secondary']"),
	DRA_LINKINGMODAL_TEXT1_XPATH("(//p[@class='ng-binding'])[1]"),
	DRA_LINKINGMODAL_TEXT2_XPATH("(//p[@class='ng-binding'])[2]"),
	DRA_LINKINGMODAL_EMAIL_CSS("span[class='wui-modal__email ng-binding']"),
	DRA_SUBSCRIPTION_INACTIVE_CSS("h2[class='login-title']"),
	DRA_SUBSCRIPTION_INACTIVE_MSG1_CSS("p[class='ng-binding']"),
	DRA_SUBSCRIPTION_INACTIVE_MSG2_XPATH("//div[@class='col-xs-10 col-xs-offset-1 text-center']/p[contains(.,'Questions?')]"),
	DRA_PROFILEFLYOUT_ACCOUNTLINK_CSS("div[class='modal-content account-content ng-scope']"),
	DRA_ACCOUNTSETTINGS_CHANGEPWD_LINK_CSS("a[class='account-option-item__link']"),
	DRA_ACCOUNTSETTINGS_CHANGEPWD_CURRENTPW_FIELD_CSS("input[name='oldPassword']"),
	DRA_ACCOUNTSETTINGS_CHANGEPWD_NEWPW_FIELD_CSS("input[name='newPassword']"),
	DRA_ACCOUNTSETTINGS_CHANGEPWD_SUBMIT_CSS("button[type='submit']"),
	DRA_ACCOUNTSETTINGS_CHANGEPWD_CANCEL_CSS("button[event-action='change-password-cancelled']"),
	DRA_CHANGEPW_ERROR_MSG_CSS("p[class='wui-input-with-label__error ng-binding ng-scope']"),
	DRA_INVALIDCREDENTIALS_ERRORMSG_CSS("label[class='wui-input-with-label__error above-form-error-message ng-scope']"),
	DRA_STEPUPAUTHMODAL_TITLE_CSS("h2[class='wui-large-text ng-binding']"),
	DRA_STEPUPAUTHMODAL_TEXT1_CSS("p[class='ng-binding ng-scope']"),
	DRA_STEPUPAUTHMODAL_TEXT2_XPATH("(//p[@class='ng-binding'])[1]"),
	DRA_STEPUPAUTHMODAL_TEXT3_XPATH("//p[contains(.,'Cortellis')]"),
	DRA_STEPUPAUTHMODAL_FORGOTPW_LINK_CSS("a[class='forgot-password__link']"),
	DRA_STEPUPAUTHMODAL_FORGOTPW_PAGE_CSS("div[class='forgot-password-header']"),
	DRA_STEPUPAUTHMODAL_LEARNMORE_CSS("a[event-action='learn-more-dra']"),
	
	// DRA_PROFILE_FLYOUT_NAME_CSS("div[class='wui-profile-flyout__info'] div[class*='wui-subtitle
	// wui-profile-flyout__name ng-binding']"),
	DRA_PROFILE_FLYOUT_NAME_CSS("div[class='dropdown-menu wui-flyout__menu wui-flyout--profile__menu'] div[class='wui-profile-flyout__info'] div"),
	DRA_PROFILE_FIRSTNAME_ERRORMSG_CSS("label[class='wui-input__error ng-scope']"),

	DRA_PROFILE_CSS("div[class='header-profile-picture']"),
	DRA_SEARCH_BOX_CSS("div[class='home-input-group']"),
	DRA_SIGNOUT_BUTTON_CSS("button[ng-click='vm.logout()']"),
	DRA_FORGOT_PASSWORD_LINK_CSS("a[class='forgot-password__link']"),
	DRA_BGCOLOR_CLASS_CSS("div[class='flex-center-horizontally']"),
	DRA_PROFILE_FLYOUT_IMAGE_CSS("div[class*='wui-profile-flyout'] a[data-toggle='dropdown']"),
	DRA_PROFILE_FLYOUT_INFO_CSS("div[class='dropdown-menu wui-flyout__menu wui-flyout--profile__menu'] div[class='wui-profile-flyout__info'] div"),
	DRA_PROFILE_FLYOUT_FOOTER_LINKS_CSS("div[class='wui-profile-flyout__footer']"),
	DRA_PROFILE_FLYOUT_HEADER_IMAGE_CSS("img[class='wui-profile-flyout__image wui-circle']"),
	DRA_PROFILE_UPDATE_CSS("button[class='wui-btn wui-btn--primary wui-btn--modal-footer']"),
	DRA_PROFILE_CANCEL_CSS("button[class='wui-btn wui-btn--secondary wui-btn--modal-footer']"),
	DRA_PROFILE_IMAGE_EDIT_CSS("button[aria-label*='Change']"),
	DRA_PROFILE_IMAGE_DELETE_CSS("button[aria-label*='Delete']"),
	DRA_FORGOT_PASSWORD_VERIFICATION_BUTTON_CSS("button[class='pull-right wui-btn login-button button-color-primary wui-btn--primary']"),
	DRA_FORGOT_PASSWORD_TEXT_XPATH("//h3[contains(text(),'Email Sent')]"),
	DRA_OK_BUTTON_XPATH("//button[contains(text(),'OK')]"),
	DRA_EVICT_MSG_XPATH("//h2[contains(text(),'Your account has been evicted.')]"),
	DRA_APP_SWITCHER_LINK_CSS("a[class='ne-app-switcher-flyout__link ne-app-switcher-flyout__link--dra']"),

	SIGNUP_PAGE_PASSWORD_TO_LONG_XPATH("(//div[@class='row password-validator__item ng-scope'])[12]/h6"),
	SIGNUP_PAGE_RED_CROSS_SYSMBOL_XPATH("(//div[@class='row password-validator__item ng-scope'])[12]//div[@class='col-xs-1 password-validator__icon fa color-c5-red fa-times']"),
	ACCOUNT_PAGE_LAST_LOGIN_TIME_CSS("div[class='source-sans--normal--italic account-option-item__last-sign-in ng-binding']"),
	ACCOUNT_PAGE_CHANGE_PASSWORD_LINK_OLD_PASSWORD_FIELD_CSS("input[name='oldPassword']"),
	ACCOUNT_PAGE_CHANGE_PASSWORD_LINK_NEW_PASSWORD_FIELD_CSS("input[name='newPassword']"),
	ACCOUNT_PAGE_CHANGE_PASSWORD_LINK_SUBMIT_BUTTON_XPATH("//span[contains(text(),'Submit')]"),
	ACCOUNT_PAGE_CHANGE_PASSWORD_LINK_CANCEL_BUTTON_XPATH("//a[contains(text(),'Cancel')]"),

	NEON_HELP_FEEDBACK_XPATH("//a[contains(text(),'Help & Feedback')]"),
	NEON_SEND_FEEDBACK_TO_NEONTEAM_XPATH("//a[contains(text(),'Send feedback to the Project Neon team')]"),

	NEON_FB_LOGIN_CONTINUE_BUTTON_XPATH("//button[@name='__CONFIRM__']"),
	NEON_SWITCH_APPS_CSS("i[class='wui-icon wui-icon--app']"),
	NEON_SWITCH_APPS_ENDNOTE_LINK_CSS("a[class='ne-app-switcher-flyout__link ne-app-switcher-flyout__link--endnote']"),
	NEON_GOT_IT_DISPLAYED_CSS("button[class='close wui-btn wui-btn--primary pull-right']"),

	// ********************IPA Locators*****************************
	NEON_IPA_USERNAME_CSS("[name='loginEmail']"),
	NEON_IPA_PASSWORD_CSS("input[name='loginPassword']"),
	NEON_IPA_SIGNIN_CSS("button[event-action='thomsonreuters']"),
	NEON_IPA_TR_TITTLE_CSS("[class*='logo-link']"),
	NEON_IPA_APP_SWITCHER_CSS("a[class='wui-flyout__toggle']"),
	NEON_IPA_PROFILE_ICON_CSS("a[class*='profile-flyout--trigger']"),
	NEON_IPA_IPA_LINK_CSS("a[data-ui-sref^='home.search']"),
	NEON_IPA_NEW_SEARCH_LINK_CSS("span[ng-click='header.newSearch()']"),
	NEON_IPA_SAVE_SEARCH_LINK_CSS("span[data-ui-sref='savedWork']"),

	NEON_IPA_EXPLORE_LABEL_CSS(".ipa-home-search--header"),
	NEON_IPA_TECHNOLOGY_LINK_CSS("div[href*='technology']"),
	NEON_IPA_COMPANY_LINK_CSS("div[href*='company']"),
	NEON_IPA_SEARCH_TEXTBOX_CSS("input[ng-model='vm.searchParam']"),
	NEON_IPA_EXPLORE_BUTTON_CSS("button[title='Search']"),

	NEON_IPA_SUGGESTION_COINTAINER_CSS("div[suggestion-data]"),
	NEON_IPA_SHOW_ALL_LINK_XPATH("//a[text()='SHOW ALL']"),

	NEON_IPA_TECH_SUG_TEXT_VAR_CSS("li[index='$index'] span[ng-bind-html*='suggestion.value']"),
	NEON_IPA_TECH_SUG_HITS_VAR_CSS("li[index='$index'] span[ng-if='suggestion.count']"),
	NEON_IPA_TECH_SUG_ADD_VAR_CSS("li[index='$index'] button"),

	NEON_IPA_DASH_PATENTS_FOUND_CNT_CSS("span[class*='patents-found__value']"),
	NEON_IPA_DASH_TAB_SEL_CSS("li[class*='ipa-content-tabs--list-item ng-scope ipa-content-tabs--list-item__active']"),
	NEON_IPA_DASH_KEYWORDS_LINK_CSS("[popover-template]"),

	NEON_IPA_DASH_TECH_COM_CSS("svg[class]"),
	NEON_IPA_DASH_COM_CSS("div[class='wui-chart']"),
	NEON_IPA_DASH_TECH_COM_X_CSS("svg.nvd3-svg  g[class='nv-x nv-axis nvd3-svg'] text[class='nv-axislabel']"),
	NEON_IPA_DASH_TECH_COM_Y_CSS("svg.nvd3-svg  g[class='nv-y nv-axis nvd3-svg'] text[class='nv-axislabel']"),
	NEOM_IPA_DASH_TECH_COM_Y_VALUES_CSS("svg.nvd3-svg  g[class='nv-y nv-axis nvd3-svg']  g[class^='tick'] text"),
	NEON_IPA_DASH_TECH_COM_COMPANYNAME_CSS("[class='key']"),
	NEON_IPA_DASH_TECH_COM_COMPANYVALUE_CSS("[class='value']"),
	NEON_IPA_DASH_TECH_COM_PATENTCOUNT_CSS("[class='x-value']"),
	NEON_IPA_DASH_BOARD_SAVE_BUTTON_CSS("div[class*='ipa-dashboard--heading'] button[ng-click*='saveSearch']"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_CSS("[name='itemName']"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_TEXT_CSS("h3[class='wui-modal__title']"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_TITLE_CSS("div[class='wui-input'] input"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_DESC_CSS("div[class='wui-textarea'] textarea"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_SAVE_BUTTON_CSS("button[type='submit']"),
	NEON_IPA_DASH_BOARD_SAVE_MODAL_CANCEL_BUTTON_CSS("button[class='wui-btn wui-btn--secondary wui-btn--modal-footer']"),
	NEON_IPA_HOMOE_PAGE_SAVED_WORK_BUTTON_CSS("span[data-ui-sref='savedWork']"),
	NEON_IPA_SAVED_DATA_PAGE_SEARCH_RECORDS_CSS("div[class='wui-card__content ng-scope']"),
	NEON_IPA_SAVED_DATA_PAGE_SEARCH_TITLE_CSS("div[class='wui-content-title wui-content-title--medium ng-binding']"),
	NEON_IPA_SAVED_DATA_PAGE_SEARCH_TERM_TYPE_CSS("span[class='wui-super-header__sse-item-text ng-binding']"),
	NEON_IPA_SAVED_DATA_PAGE_EDIT_BUTTON_CSS("button[ng-click='vm.setItemEditMode(item)']"),
	NEON_IPA_SAVED_DATA_PAGE_DELETE_BUTTON_CSS("button[ng-click='vm.openDeleteModal(item)']"),
	NEON_IPA_PROFILEFLYOUT_CSS("img[class='wui-circle']"),
	NEON_IPA_ACCOUNT_CSS("a[class='wui-profile-flyout__link wui-profile-flyout__link--icon']"),
	NEON_IPA_ACCOUNTNAME_CSS("span[class='ng-binding']"),
	NEON_IPA_TECH_SEARCHBOX_CSS("div[class='ipa-search-input-control__input-group'] input"),
	
	NEON_IPA_TECH_SEARCHSUGGESTIONS_XPATH("//div[starts-with(@ng-click,'vm.select')]"),
	NEON_IPA_TECH_CLIPBOARD_CSS("ipa-search-term[class='ng-isolate-scope'] li[ng-repeat='item in vm.items track by $index']"),
	NEON_IPA_TECH_NEWSEARCH_XPATH("//*[contains(text(),'Search')]"),
	NEON_IPA_TECHHIGHLIGHT_XPATH("//*[contains(text(),'Technology areas')]/hr[@class='ipa-tabs--underline ipa-tabs--underline__active']"),
	NEON_IPA_COMPANYHIGHLIGHT_XPATH("//*[contains(text(),'Company portfolios')]/hr[@class='ipa-tabs--underline ipa-tabs--underline__active']"),
	NEON_IPA_EXPLOREBUTTON_XPATH("//button[contains(text(),'Explore')]"),
	NEON_IPA_TECHNOLOGYSEARCH_CSS("[ui-sref='home.search({type: \\'technology\\'})']"),
	NEON_IPA_COMPANYSEARCH_CSS("[ui-sref='home.search({type: \\'company\\'})"),
	NEON_IPA_HEADER_CSS("span[ng-click*='header.newSearch()']"),
	NEON_IPA_TECHPORTFOLIO_CSS("li[class='ipa-content-tabs--list-item ng-scope ipa-content-tabs--list-item__active']"),
	NEON_IPA_CHART_CSS("svg[class='nvd3-svg']"),
	NEON_IPA_COMPANYWATERMARK_CSS("Enter a company you're interested in (eg. Ford Motor Co)"),
	NEON_IPA_COMPANYCLIPBOARD_CSS("li[ng-repeat='item in vm.items track by \\$index'][class='search-term__item ng-scope']"),
	NEON_IPA_NONSELECTED_TABS_CSS("li[class='ipa-content-tabs__list-item ng-scope']"),

	IPA_BRANDING_NAME_CSS("h3[class='wui-title login-header__app-name ng-binding']"),
	IPA_LOGO_CSS("h4[class='wui-title login-header__app-name ng-binding']"),
	IPA_NEW_LOGO_CSS("img[class='login-logo']"),
	IPA_LANDINGPAGE_TERMS_LINK_CSS("a[data-event-action='login-terms-of-use']"),
	IPA_LANDINGPAGE_PRIVACY_LINK_CSS("a[data-event-action='login-privacy-statement']"),
	IPA_LANDINGPAGE_HELP_MESSAGE_CSS("p[class='tos']"),
	IPA_LANDINGPAGE_SUPPORT_MAILID_CSS("p[class='tos ng-scope'] >a[event-action='login-customer-care-ipa']"),
	IPA_LANDINGPAGE_EXPLORE_ICON_CSS("i[class='fa fa-compass login-splash-icon']"),
	IPA_LANDINGPAGE_ANALYZE_ICON_CSS("i[class='wui-icon wui-icon--analyze login-splash-icon']"),
	IPA_LANDINGPAGE_VISUALIZE_ICON_CSS("i[class='fa fa-pie-chart login-splash-icon']"),
	IPA_LANDINGPAGE_REPORT_ICON_CSS("i[class='fa fa-signal login-splash-icon']"),
	IPA_LINKINGMODAL_TEXT1_XPATH("(//p[@class='ng-binding'])[1]"),
	IPA_LINKINGMODAL_TEXT2_XPATH("(//p[@class='ng-binding'])[2]"),
	IPA_LINKINGMODAL_EMAIL_CSS("span[class='wui-modal__email ng-binding']"),
	IPA_ACCOUNTSETTINGS_CHANGEPWD_SUBMIT_CSS("button[data-event-action='change-password-submitted']"),
	IPA_ACCOUNTSETTINGS_CHANGEPWD_CANCEL_CSS("button[event-action='change-password-cancelled']"),
	IPA_APP_SWITCHER_LINK_CSS("a[class='ne-app-switcher-flyout__link ne-app-switcher-flyout__link--ipa']"),
	IPA_STEPUPAUTHMODAL_TEXT1_CSS("p[class='ng-scope']"),
	IPA_PROFILE_FLYOUT_IMAGE_CSS("a[class='wui-profile-flyout--trigger wui-circle']"),
	NEON_IPA_VISUALIZATION_PIN_CSS("i[class='fa pin__icon fa-thumb-tack']"),
	NEON_IPA_SELECTED_TABS_CSS("li[class='ipa-content-tabs__list-item ng-scope ipa-content-tabs__list-item--active']"),
	NEON_IPA_DISPLAYED_GRAPHS_CSS("div[ng-repeat='pin in Dashboard.pins.getPins()']"),

	IPA_ACCOUNTSETTINGS_CLOSEBUTTON_CSS("button[class='wui-modal__close-btn']"),
	NEON_PROJECTNEON_APP_SWITCHER_CSS("a[class='wui-app-switcher__link wui-app-switcher__link--neon']"),
	IPA_CANCEL_BUTTON_IN_SAVED_DATA_TILE_CSS("button[ng-click='vm.cancelItemEditMode(item)']"),
	IPA_DELETE_SAVED_ITEM_BUTTON_POPUP_TEXT_CSS("div[class='modal-body wui-modal__body'] p"),
	IPA_DELETE_BUTTON_IN_SAVED_CONFIRMATION_MODAL_CSS("button[class='wui-btn wui-btn--primary wui-btn--modal-footer']"),
	IPA_SAVE_BUTTON_IN_SAVED_DATA_TILE_CSS("button[class='wui-mini-btn wui-mini-btn--primary']"),
	DR_SEARCH_CLICK_CSS("button[class='wui-search-bar__search-button']"),
	DR_SEARCH_RESULT_CSS("p[class='wui-title']"),
	DRA_ACCOUNT_CROSS_CSS("i[class='fa fa-close']"),

	// #################### IAM ##########################
	// NEON_LOGIN_PAGE_FORGOT_PASSWORD_SEND_EMAIL_CSS("input[name='loginEmail']"),
	NEON_LOGIN_PAGE_FORGOT_PASSWORD_TEXT_CSS("div[class='forgot-password-header']"),
	NEON_LOGIN_PAGE_FORGOT_PASSWORD_SEND_EMAIL_BUTTON_CSS("button[class='pull-right wui-btn wui-btn--send-email wui-btn--primary']"),
	NEON_LOGIN_PAGE_FORGOT_PASSWORD_OK_CSS("button[class='pull-right wui-btn wui-btn--primary wui-btn--login'] span"),
	NEON_RESEND_EMAIL_BUTTON_CSS("button[class='pull-right wui-btn wui-btn--primary wui-btn--login'] "),
	GURILLA_RECEIVED_MAIL_SUBJECT_CSS("h3[class='email_subject']"),
	GURILLA_MAIL_BODY_PASSWORD_RESET_LINK_XPATH("//*[@class='email_body']//a"),
	RESET_PASSWORD_PAGE_CHECK_VALIDATIONS_CSS("div[class='row password-validator__item ng-scope']"),
	RESET_PASSWORD_PAGE_CHECK_SUCCESS_TICK_MARK_CSS("div[class='col-xs-1 password-validator__icon fa text-success fa-check']"),
	RESET_PASSWORD_PAGE_CHECK_SUCCESS_TICK_MARK_MESSAGE_CSS("H6[class='col-xs-11 password-validator__text ng-binding']"),
	LOGIN_PAGE_FORGOT_PASSWORD_LINK_CSS("a[class='forgot-password__link']"),
	GURILLA_LIST_EMAIL_IDS_XPATH("//tr[starts-with(@id,'mr_')]/td[2]"),
	GURILLA_LIST_EMAIL_PROJECT_TITLE_CSS("span[style='color:#45B7E7;']"),
	RESET_YOUR_PASSWORD_PAGE_CSS("div[class='row ng-scope'] div"),
	RESET_YOUR_PASSWORD_PAGE_TEXT_BOX_CSS("div[class='wui-input-with-label'] input"),
	RESET_YOUR_PASSWORD_PAGE_RESET_BUTTON_CSS("div[class='login-button-container'] button"),
	NEON_LOGIN_PAGE_FORGOT_PASSWORD_PAGE_CALCEL_BUTTON_CSS("div[class='login-button-container'] a"),
	FORGOT_PASSWORD_PAGE_ERROR_MESSAGE_CSS("label[class='wui-input-with-label__error ng-scope']"),
	GURILLA_LIST_EMAIL_ENW_PROJECT_TITLE_CSS("span[style*='color:#FF9100;']"),
	GURILLA_LIST_EMAIL_DRA_PROJECT_TITLE_CSS("span[style*='color:#B1CD43;']"),
	GURILLA_LIST_EMAIL_IPA_PROJECT_TITLE_CSS("span[style*='color:#621F95;']"),

	NEON_IPA_SEARCH_TERMS_LABEL_CSS("div[class^='search-term__label']"),
	NEON_IPA_SEARCH_TERMS_LABEL_NEW_CSS("span[ng-repeat='item in vm.clipboard.getDisplayDb(vm.type) | limitTo: 4 track by $index']>div>button>div"),
	NEON_IPA_SEARCH_TERMS_REMOVE_CSS("div[ng-click^='vm.removeItem']"),
	NEON_IPA_SEARCH_TERMS_CSS("li[class^='search-term__item']"),
	NEON_IPA_SEARCH_TERMS_DASHBOARD_CSS("div[class='search-term__label ng-binding']"),
	NEON_IPA_SEARCH_TERMS_DASHBOARD_LABEL_CSS("ipa-search-items[type='Dashboard.queryType'] button[id='split-button']"),
	NEON_IPA_TECH_SUG_DROPDOWN_CSS("div[class^='typeahead-results']"),
	NEON_IPA_TECH_NEW_SEARCH_HEADER_LINK_CSS("span[ng-click='header.newSearch()']"),
	NEON_IPA_SEARCH_TERM_PRESELECTED_SYNMS_CSS("li input[type='checkbox'][checked='checked']"),
	NEON_IPA_SEARCH_TERM_PRESELECTED_SYNMS_DB_CSS("ipa-search-items[type='Dashboard.queryType'] li div input[checked='checked']"),
	NEON_IPA_SEARCH_TERM_DROP_DOWN_ICON_CSS("button[id='split-button'] div[class='search-term__label ng-binding']"),
	NEON_IPA_SEARCH_TERM_SYNMS_LIST_CSS("li[class^='search-term__item'] li input[type='checkbox']"),
	NEON_IPA_SEARCH_TERM_SYNMS_LIST_DB_CSS("ipa-search-items[type='Dashboard.queryType'] li input[type='checkbox']"),
	NEON_IPA_TECH_SHOW_ALL_LINK_CSS("button[class*='typeahead-results__showall']"),
	IPA_SAVED_DATA_PAGE_SORT_BUTTON_CSS("button[id='sort-sse-items']"),
	IPA_SAVED_DATA_PAGE_SORT_MENU_CSS("ul[class='dropdown-menu sse-dropdown__menu'] li"),
	IPA_RECORD_VIEW_PAGE_PATENT_TITLE_CSS("h2[class^='wui-content-title']"),
	NEON_IPA_COMPANY_TYPE_AHAED_LABEL_CSS("div[class='typeahead-results-list__item']"),
	NEON_IPA_DASH_BOARD_PATENT_FOUND_ICON_CSS("ul[class='ipa-content-tabs']>li:nth-of-type(4)"),
	NEON_IPA_TECH_SUG_LIST_CSS("li[index='$index']"),
	NEON_IPA_RECORD_LIST_PAGE_PATENT_TITLE_CSS("a[data-event-category='searchresult-ck-patents']"),
	NEON_IPA_DASH_BOARD_PATENT_FOUND_COUNT_CSS("span[class^='patents-found__value']"),
	IPA_RECORD_VIE_PAGE_PATENTS_INFO_CSS("div [class='ipa-patent--list-items'] li"),
	IPA_RECORD_VIEW_PAGE_PANTENTS_RHS_TILE_CSS("h6[class='ipa-patent--legal-status']"),
	IPA_RECORD_VIEW_PAGE_PATENT_PDF_LINK_CSS("div[class='ipa-patent--legalinfo'] a[target='_blank']"),
	IPA_RECORD_VIE_PAGE_VALIDATE_TEXT_INFO_CSS("div [class='ipa-patent--description'] strong"),
	IPA_RECORD_VIEW_MORE_LINK("more..."),
	IPA_DASHBOARD_PAGE_GRAPH_IMAGE_CSS("div[class='col-md-12']"),
	NEON_IPA_DASH_PAT_SEL_DD_CSS("select[ng-model='sortVm.item']"),
	// Technology Terms
	NEON_IPA_DASH_TECH_KEY_STRENGTH_XPATH("//*[text()='Average strength']"),
	NEON_IPA_DASH_TECH_KEY_STRENGTH_VAL_XPATH("//*[text()='Average strength']/../div"),
	NEON_IPA_DASH_TECH_KEY_APP_LAST5_XPATH("//*[text()='Applications in last 5 years']"),
	NEON_IPA_DASH_TECH_KEY_APP_LAST5_VAL_XPATH("//*[text()='Applications in last 5 years']/../div"),
	NEON_IPA_DASH_TECH_KEY_TOPFILERS_XPATH("//*[text()='Top filers']"),
	NEON_IPA_DASH_TECH_KEY_TOPFILERS_VALS_XPATH("//*[text()='Top filers']/../div/div"),
	NEON_IPA_DASH_TECH_KEY_TOPTECH_TERMS_XPATH("//*[text()='Top technology terms']"),
	NEON_IPA_DASH_TECH_KEY_TOPTECH_TERMS_VALS_XPATH("//*[text()='Top technology terms']/../div/div"),
	// Company Terms
	NEON_IPA_DASH_COM_KEY_PUB_XPATH("//*[text()='Publications']"),
	NEON_IPA_DASH_COM_KEY_PUB_VAL_XPATH("//*[text()='Publications']/../div"),
	NEON_IPA_DASH_COM_KEY_LIVE_PATENT_XPATH("//*[text()='Live patents']"),
	NEON_IPA_DASH_COM_KEY_LIVE_PATENT_VAL_XPATH("//*[text()='Live patents']/../div"),
	NEON_IPA_DASH_COM_KEY_FAMILIES_XPATH("//*[text()='Families']"),
	NEON_IPA_DASH_COM_KEY_FAMILIES_VAL_XPATH("//*[text()='Families']/../div"),
	NEON_IPA_DASH_COM_KEY_STRENGTH_XPATH("//*[text()='Average strength']"),
	NEON_IPA_DASH_COM_KEY_STRENGTH_VAL_XPATH("//*[text()='Average strength']/../div"),
	NEON_IPA_DASH_COM_KEY_CUR_OWNER_XPATH("//*[text()='Current owner']"),
	NEON_IPA_DASH_COM_KEY_CUR_OWNER_VAL_XPATH("//*[text()='Current owner']/../div"),
	NEON_IPA_DASH_COM_KEY_PARENT_XPATH("//*[text()='Parent']"),
	NEON_IPA_DASH_COM_KEY_PARENT_VAL_XPATH("//*[text()='Parent']/../div"),
	NEON_IPA_DASH_COM_KEY_TOP_TEC_TERMS_XPATH("//*[text()='Top technology terms']"),
	NEON_IPA_DASH_COM_KEY_TOP_TEC_TERMS_VALS_XPATH("//*[text()='Top technology terms']/../div/div"),
	NEON_IPA_DASH_COM_KEY_TOP_COUNTRIES_XPATH("//*[text()='Average strength']"),
	NEON_IPA_DASH_COM_KEY_TOP_COUNTRIES_VALS_XPATH("//*[text()='Top countries']/../div/div"),
	NEON_IPA_RESULTLIST_PUBLICATION_NUMS_CSS("[ng-hide='!vm.record.patent'] >span:nth-of-type(2)"),
	NEON_IPA_RESULTLIST_PUBLICATION_DATES_CSS("[ng-hide='!vm.record.pubDate']"),
	NEON_IPA_RESULTLIST_ASSIGNEES_CSS("[ng-hide*='vm.record.assignee']"),
	NEON_IPA_RESULTLIST_ULIMATE_PATENTS_CSS("[ng-hide*='!vm.record.owner']"),
	NEON_IPA_RESULTLIST_DWPI_TITLES_CSS("div[class*='content-title']>a[data-analytics-event]"),
	NEON_IPA_RESULTLIST_RELAVENCES_CSS("[ng-hide*='.record.relevance']"),
	NEON_IPA_RESULTLIST_LIVE_STATUS_CSS("[ng-hide*='record.aliveStatus']"),
	NEON_IPA_RESULTLIST_EXPIRATION_DATES_CSS("[ng-hide*='record.expiration']"),
	NEON_IPA_RESULTLIST_DWPI_IMAGES_CSS("img[src][class*='col']"),
	NEON_IPA_RESULTLIST_PDF_LINKS_CSS("[ng-hide*='record.aliveStatus']>a"),

	NEON_IPA_RECORDVIEW_NEXT_CSS("[ng-click*='vm.nextPage()']"),
	NEON_IPA_RECORDVIEW_STRENGTH_CSS("[ng-hide*='patent.patentStrength']>span:nth-of-type(2)"),
	NEON_IPA_RECORDVIEW_CURRENTPAGE_CSS("[class*='ng-binding current-page']"),
	NEON_IPA_RECORDVIEW_EXPIRYDATE_CSS("li[ng-hide*='patent.expiration'] span:nth-of-type(2)"),
	NEON_IPA_DASH_TECH_COM_TAB_CSS("div[event-category*='competitors']") ,
	NEON_IPA_DASH_TECH_TEC_TAB_CSS("div[event-category*='trend']"),
	NEON_IPA_DASH_TECH_PAN_TAB_CSS("div[event-category*='patents']"),
	NEON_IPA_DASH_KEYINFORMATION_PANEL_CSS("div.popover-content"),
	NEON_IPA_DASH_TITLE_CSS("div[class*='dashboard--heading-primary']"),
	NEON_IPA_DASH_TECH_COM_X_MIN_CSS("g[class$='nv-axisMin-x']>text"),
	NEON_IPA_DASH_TECH_COM_X_MAX_CSS("g[class$='nv-axisMax-x']>text"),
	NEON_IPA_DASH_TECH_COM_Y_MIN_CSS("g[class$='nv-axisMin-y']>text"),
	NEON_IPA_DASH_TECH_COM_Y_MAX_CSS("g[class$='nv-axisMax-y']>text"),
	NEON_IPA_DASH_TECH_COM_TOP_IPC_CSS("svg.nvd3-svg g[class*='nvd3 nv-legend'] g[class='nv-series']:nth-of-type($index)>text"),
	NEON_IPA_DASH_KEYINFORMATION_LINK_CSS("div[class*='dashboard__header']:nth-of-type(3) a[class='popover-target']"),
	NEON_IPA_SAVED_SEARCH_PAGE_TILE_DESC_CSS("div[class='sse-item-description ng-binding']"),
	NEON_IPA_SAVED_SEARCH_PAGE_TILE_TITLE_CSS("div[class='wui-content-title wui-content-title--medium ng-binding'"),
	NEON_IPA_SAVED_SEARCH_PAGE_LAST_VIEWED_CSS("span[class='wui-label wui-label--sse-item-last-viewed-date ng-scope'] wui-timestamp"),
	NEON_IPA_SAVED_SEARCH_PAGE_SAVED_VALUE_CSS("span[class='wui-label ng-scope'] wui-timestamp"),
	
	NEON_IPA_VIEWBY_ALL_CSS("button[ng-class*='undefined']"),
	NEON_IPA_VIEWBY_UTILITY_CSS("button[ng-class*='U']"),
	NEON_IPA_VIEWBY_GRANT_CSS("button[ng-class*='G']"),
	NEON_IPA_VIEWBY_APPLICATION_CSS("button[ng-class*='A']"),
	NEON_IPA_VIEWBY_Familiy_CSS("button[ng-class*='Basic']"),
	NEON_IPA_VIEWBY_Publication_CSS("button[ng-class*='grantStatus']"),
	
	NEON_IPA_DASH_LINK_SEARCHTERM_CSS("a[ng-click*='search']"),
	NEON_IPA_DASH_SEARCHTERMS_CSS("[type='Dashboard.queryType'] button[id='split-button']"),
	NEON_IPA_SEARCH_TAB_TEXT_CSS("input[ng-model='vm.searchParam']"),
	NEON_IPA_SEARCH_TAB_ADD_TERM_XPATH("//text()[   contains(     translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'),'$value') ]/../../../button"),

	IPA_CC_NAME_CSS("input[ng-model='vm.fullName']"),
	IPA_CC_ORG_NAME_CSS("input[ng-model='vm.organization']"),
	IPA_CC_EMAIL_CSS("input[type='email']"),
	IPA_CC_PHONE_CSS("input[type='tel']"),
	IPA_CC_COUNTRY_NAME("category"),
	IPA_CC_HEADER_CSS("h2[class='cc-sub-nav__title cc-sub-nav__title--ipa']"),
	
	DRA_CC_HEADER_CSS("h3[class='cc-sub-nav__subtitle cc-sub-nav__subtitle--dra']"),
	DRA_CC_HEADER_TD_CSS("h2[class='cc-sub-nav__title cc-sub-nav__title--dra']"),
	
	
	
	// #################### CUSTOMER CARE ##########################
	CUSTOMER_CARE_USER_NAME_ID("login"),
	CUSTOMER_CARE_PASSWORD_ID("userPassword"),
	CUSTOMER_CARE_CLICK_LOGIN_BUTTON_ID("GO"),
	CUSTOMER_CARE_MENU_PANEL_NAME("MenuPanel"),
	CUSTOMER_CARE_MAIN_PANEL_NAME("MainPanel"),
	CUSTOMER_CARE_HEADER_PANEL_NAME("HeaderPanel"),
	CUSTOMER_CARE_CREATE_USER_FIRSTNAME_NAME("firstName"),
	CUSTOMER_CARE_CREATE_USER_LASTNAME_NAME("lastName"),
	CUSTOMER_CARE_CREATE_USER_APPLICATIONID_ID("applicationId"),
	CUSTOMER_CARE_CREATE_USER_SET_PASSWORD_ID("passwordOptionsDD"),
	CUSTOMER_CARE_CREATE_USER_PASSWORD_NAME("userPassword"),
	CUSTOMER_CARE_CREATE_USER_CONFORM_PASSWORD_NAME("confirmPassword"),
	CUSTOMER_CARE_CREATE_USER_MAIL_NAME("mailId"),
	CUSTOMER_CARE_CREATE_USER_REGISTER_BUTTON_NAME("Register"),
	CUSTOMER_FIND_USER_NAME("finduser"),
	CUSTOMER_ENTER_CLIME_TICKET_NAME("claimTicket"),
	CUSTOMER_CLICK_ASSOCIATE_BUTTON_NAME("associate"),
	GURILLA_MAIL_TEXT_ID("email-widget"),
	CUSTOMER_CARE_LOGIN_PAGE_NAME("loginform"), 
	CUSTOMER_CARE_CALLUS_DROPDOWN_CSS("select[ng-model='vm.region']"),
	CUSTOMER_CARE_CALLUS_CTRY1_XPATH("(//p[@class='cc-content ng-binding ng-scope'])[1]"),
	CUSTOMER_CARE_CALLUS_CTRY2_XPATH("(//p[@class='cc-content ng-binding ng-scope'])[2]"),
	DRA_FEEDBACKLINK_CSS("ul[class='wui-profile-flyout__list'] li:nth-child(4)"),
DRA_HELPLINK_CSS("ul[class='wui-profile-flyout__list'] li:nth-child(3)"),
	
	CUSTOMER_CARE_SUPPORTLINK_FEEDBACK_CSS("a[href*='thomsonreuters.com']"),
	CUSTOMER_CARE_SUPPORTLINK_HELP_CSS("a[href='/#/customer-care?app=dra']"),
	CUSTOMER_CARE_SUPPORTREQUEST_NAME_CSS("input[placeholder^='Name']"),
	CUSTOMER_CARE_SUPPORTREQUEST_ORG_CSS("input[placeholder^='Organization']"),
	CUSTOMER_CARE_SUPPORTREQUEST_EMAIL_CSS("input[placeholder^='Email address']"),
    DRA_PROFILEDATA_CSS("div[class='wui-subtitle wui-profile-flyout__name ng-binding']"),
	DRA_PROFILE_FNAME_CSS("input[placeholder='+ First Name']"),
	DRA_PROFILE_LNAME_CSS("input[placeholder='+ Last Name']"),
	DRA_PROFILE_ORG_CSS("input[placeholder='+ Institution']"),
	DRA_PROFILE_COUNTRY_CSS("input[placeholder='+ Country']"),

	
	
	CUSTOMER_CARE_CALLUS_SECTION_CSS("div[class='cc-call-us'] h4"),
	CUSTOMER_CARE_REQUEST_SECTION_CSS("div[class='cc-contact-form'] h4"),
	CUSTOMER_CARE_REGION_CSS("strong[class='wui-emphasis ng-binding']"),
	CUSTOMER_CARE_HRS_XPATH("(//p[@class='cc-content ng-binding'])[1]"),
	CUSTOMER_CARE_LANGUAGE_XPATH("(//p[@class='cc-content ng-binding'])[2]"),
	CUSTOMER_CARE_USER_FULLNAME_NAME("fullName"),
	CUSTOMER_CARE_USER_ORGANIZATION_NAME("organization"),
	CUSTOMER_CARE_USER_EMAILID_NAME("email"),
	CUSTOMER_CARE_USER_PHONE_NAME("phone"),
	CUSTOMER_CARE_USER_EXTN_NAME("extension"),
	CUSTOMER_CARE_USER_COUNTRY_NAME("country"),
	CUSTOMER_CARE_USER_CATEGORY_NAME("category"),
	CUSTOMER_CARE_USER_REQUEST_NAME("request"),
	CUSTOMER_CARE_SUBMIT_BUTTON_CSS("button[ng-click='vm.submitRequest()']"),
	CUSTOMER_CARE_USER_REQUEST_MSG_CSS("h3[class='wui-subtitle']"),
	CUSTOMER_CARE_USER_REQUEST_MSG1_CSS("div[class='modal-body wui-modal__body ng-scope'] p:nth-child(1)"),
	CUSTOMER_CARE_USER_REQUEST_MSG2_CSS("div[class='modal-body wui-modal__body ng-scope'] p:nth-child(2)"),
	CUSTOMER_CARE_USER_OK_BUTTON_CSS("button[class='wui-btn wui-btn--primary']"),
	DRA_CUSTOMER_CARE_LINK_CSS("a[data-event-category='dra-customer-care']"),
	CUSTOMER_CARE_PHONE_NAME_ERROR_MESSAGE_XPATH("//span[@class='wui-input__error wui-input__error--cc-contact-form']"),
	CUSTOMER_CARE_CLEARBTN_XPATH("//button[@class='wui-btn wui-btn--secondary']"),
	
	;

	private String locator;

	OnePObjectMap(String locator) {
		this.locator = locator;
	}

	public String toString() {
		return this.locator;
	}
}
